- src/Toolbar/Toolbar.example.jsx
- src/Toolbar/Toolbar.example.md
- src/Toolbar/Toolbar.jsx
- src/Toolbar/Toolbar.less
- src/Toolbar/Toolbar.spec.jsx
- src/index.js
- webpack.examples.config.js
Title says it all. Please review.
> Adds toolbar container, its tests and examples

- .eslintrc
- example-templates/basicMap.html
- src/Map/FloatingMapLogo/FloatingMapLogo.example.jsx
- src/Map/FloatingMapLogo/FloatingMapLogo.example.md
- src/Map/FloatingMapLogo/FloatingMapLogo.jsx
- src/Map/FloatingMapLogo/FloatingMapLogo.less
- src/Map/FloatingMapLogo/FloatingMapLogo.spec.jsx
- src/Map/ScaleCombo/ScaleCombo.example.jsx
- src/Map/ScaleCombo/ScaleCombo.example.md
- src/Map/ScaleCombo/ScaleCombo.jsx
- src/Map/ScaleCombo/ScaleCombo.spec.jsx
- src/UserChip/UserChip.example.jsx
- src/UserChip/UserChip.jsx
- src/Util/MapUtil.js
- src/Util/MapUtil.spec.js
- src/Util/TestUtils.js
- src/index.js
- webpack.examples.config.js
Introduces `FloatingMapLogo` and `ScaleCombo` components.
In addition, `MapUtil` is included here as well beside method `buildLayersFromInitialState` (see https://github.com/terrestris/react-geo/pull/12)
> Add components for floating map logo and scale combo

- src/Util/ObjectUtil.js
- src/Util/ObjectUtil.spec.js
This PR adds an `ObjectUtil` helper class from a client project. It is ported with the minimum needed changes, and with additional tests so that coveralls is happy.
Please review.
> Add ObjectUtil helper class

- package.json
Copy all non transpiled files (e.g. less files) to dist folder, but ignore example and test files.
> Ready for production dist folder

- package.json
This introduces the `react` dependency as `peerDependency`. Otherwise applications using this package may encounter the error explained [here](https://facebook.github.io/react/warnings/refs-must-have-owner.html).
> Set react as peer dependency

- src/Map/ScaleCombo/ScaleCombo.jsx
- src/Map/ScaleCombo/ScaleCombo.spec.jsx
* Map received `zoomLevel` prop to state.
* Round scale values to a multiple of 10.
* Calculate scale entries in correct order out of given map resolutions.
> Some fixes to the ScaleCombo

- .travis.yml
- package-lock.json
- package.json
This updates the following dependencies:
* Update `rimraf` to v2.6.2
* Update `react-rnd` to v7.0.0
* Update `react-i18next` to v5.3.0
* Update `mocha` to v3.5.3
* Update `loglevel` to v1.5.0
* Update `babel-eslint` to v8.0.0
And also adds a current `package-lock.json`.
* Closes #43
* Closes #44 
* Closes #45
* Closes #46 
* Closes #48 
* Closes #49
The build failures are related to https://github.com/jsdoc3/jsdoc/issues/1438, where jsdoc cannot copy files as it used to copy due to using a native node method introduced in Node.js 8.5.0 which behaves differently than their fallback. To work around this, the travis configuration is changed to build on Node.JS v8.4.0 (d530a7d9c35eb15be19606bab8390d8a7d5fe4ca).
> Update several dependencies and package-lock.json

- src/LayerTree/LayerTree.example.jsx
- src/LayerTree/LayerTree.jsx
- src/LayerTree/LayerTree.spec.jsx
- src/Util/MapUtil.js
- src/Util/MapUtil.spec.js
- Adds `visibility:change` listeners to layers in tree
- Adds `add` and `remove` listeners to grouplayers in tree
- Fixes the drag and drop behaviour
OT:
- Adds optional filter to  `MapUtil.getAllLayers`
> LayerTree improvements

- .travis.yml
Basicaly reverts d530a7d9c35eb15be19606bab8390d8a7d5fe4ca and uses the latest Node.js 8.x when building on Travis.
Please review.
> Use latest Node.js

- src/Legend/Legend.example.jsx
- src/Legend/Legend.example.md
- src/Legend/Legend.jsx
- src/Legend/Legend.spec.jsx
- src/Util/MapUtil.js
- src/Util/MapUtil.spec.js
- src/Util/UrlUtil.js
- src/Util/UrlUtil.spec.js
- webpack.examples.config.js
This introduces the `Legend` component
Also add util methods:
- MapUtil.getLegendGraphicUrl
- UrlUtil.objectToRequestString
@terrestris/devs plz review
> Introduces the Legend component

- src/Button/SimpleButton/SimpleButton.jsx
- src/Button/SimpleButton/SimpleButton.less
- src/Button/ToggleButton/ToggleButton.jsx
- src/Button/ToggleButton/ToggleButton.less
- src/Button/ToggleButton/ToggleButton.spec.jsx
- src/Button/ToggleGroup/ToggleGroup.jsx
- src/LayerTree/LayerTree.jsx
- src/Map/FloatingMapLogo/FloatingMapLogo.jsx
- src/Map/FloatingMapLogo/FloatingMapLogo.less
- src/Map/FloatingMapLogo/FloatingMapLogo.spec.jsx
- src/Map/ScaleCombo/ScaleCombo.jsx
- src/Map/ScaleCombo/ScaleCombo.spec.jsx
- src/Panel/Panel/Panel.jsx
- src/Panel/Panel/Panel.less
- src/Panel/Titlebar/Titlebar.jsx
- src/Panel/Titlebar/Titlebar.less
- src/Toolbar/Toolbar.jsx
- src/UserChip/UserChip.jsx
- src/UserChip/UserChip.less
- src/UserChip/UserChip.spec.jsx
This introduces a private `className` property and `className` as a react-property for all components.
The pattern of the components className is like: `react-geo-{class}`
A optional className from props will be added to the class to.
closes #57
> Introduces unified css-className for current classes

- src/LayerTree/LayerTree.example.jsx
- src/LayerTree/LayerTree.jsx
- src/LayerTree/LayerTree.spec.jsx
- src/Legend/Legend.spec.jsx
- src/Map/ScaleCombo/ScaleCombo.example.jsx
- src/Util/MapUtil.spec.js
- src/Util/TestUtil.js
This PR suggests to harmonize our imports, so that we have more confidence whether a class we import from 'ol/layer/group'  has to be referred to as `OlLayerGroup` or OlGroupLayer`, for example.
Please review.
Fixes #57
> Harmonize named imports

- README.md
This removes the `npm start` command as there seems to be no real use for it.
A link to the gh-pages has been added instead.
Should fix https://github.com/terrestris/react-geo/issues/84
> Add link to gh-pages, removed unused command

- .babelrc
This adjusts the `babel-plugin-import` configuration to import all `antd` style definitions via less instead of  css. From the official documentation:
Before:
```js
import { Button } from 'antd';
ReactDOM.render(<Button>xxxx</Button>);
↓ ↓ ↓ ↓ ↓ ↓
var _button = require('antd/lib/button');
require('antd/lib/button/style/css');
ReactDOM.render(<_button>xxxx</_button>);
```
Now:
```js
import { Button } from 'antd';
ReactDOM.render(<Button>xxxx</Button>);
↓ ↓ ↓ ↓ ↓ ↓
var _button = require('antd/lib/button');
require('antd/lib/button/style');
ReactDOM.render(<_button>xxxx</_button>);
```
Having this set, all modify variables an application might set, will be directly applied to all `antd` components wrapped by `react-geo`.
> Adjust babel import plugin to import LESS styles

- src/LayerTree/LayerTree.jsx
- src/LayerTree/LayerTree.spec.jsx
- src/LayerTreeNode/LayerTreeNode.jsx
- src/LayerTreeNode/LayerTreeNode.less
- src/LayerTreeNode/LayerTreeNode.spec.jsx
- src/index.js
This PR proposes some extensions to the `LayerTree`:
* Wrapping the `TreeNode` in it's own class `LayerTreeNode`.
* Currently this component doesn't do anything (except having a custom `className` set), but it may be useful for future development and/or refactoring.
* Adding the property `nodeTileRenderer`.
*  `nodeTileRenderer` is an optional function that can be used to pass a custom title to the `TreeNode` (`LayerTreeNode`). As the `TreeNode` is capable of receiving an `ReactNode`, the function can return any renderable element (String, Number, Element etc.) composition. Additionally it receives the layer instance of the current tree node as argument, so any title can do custom layer-specific stuff.
* Setting `className` and pass filtered props down to `antd` component only.
> LayerTree extensions

- src/LayerTree/LayerTree.jsx
This way we can ensure the `nodeTitleRenderer` function will be called on every prop/state/layer change.
> Rebuild treeNodes on layer visibility change

- .gitignore
This changes the already existing entry in the .gitognore file to
actually ignore the file 'C:\nppdf32Log\debuglog.txt'.
Please review.
> Ignore 'C:\nppdf32Log\debuglog.txt'

- src/Button/SimpleButton/SimpleButton.jsx
This fixes the shifted layout of the icon in `SimpleButton.`
> Remove padding from simplebutton icon

- package.json
- src/LayerTree/LayerTree.spec.jsx
- src/Map/ScaleCombo/ScaleCombo.spec.jsx
- src/Panel/Panel/Panel.spec.jsx
- src/Util/MapUtil/MapUtil.spec.js
This aims to cleanup the test environment by removing every `div`-container created by `TestUtils.createMap()`.
Additionally `test:watch` will run in `PhantomJS` only.
> Cleanup test environment

- example-templates/basic.html
- src/LayerTree/LayerTree.example.jsx
- src/LayerTree/LayerTree.jsx
- src/LayerTree/LayerTree.spec.jsx
- src/LayerTreeNode/LayerTreeNode.jsx
- src/LayerTreeNode/LayerTreeNode.less
- src/Util/MapUtil/MapUtil.js
- src/Util/MapUtil/MapUtil.spec.js
This makes it so that layers that are shown/hidden because they are scale dependant also have another class in the layer tree node. 
The code contains some TODOs we should tackle later. Generally I would suggest to put some (bigger) part of the LayerTree class into the LayerTreeNode class.
Please review.
> Basic handling of scale dependant layers

- .travis.yml
- package.json
This makes ol (openlayers) a peer dependency.
Due to several scope-/instanceof-issues with webpack we need to ensure that the react-geo and the project that uses react-geo refer to the same instance of openlayers.
Therefore we make ol a peer dependency.
Additionaly we make the versions of our peer dependencies more lenient as @marcjansen suggested. :top:
> Update peer dependencies (add ol)

- webpack.examples.config.js
Currently, the image and font resources cannot be found in the examples, as reported in https://github.com/terrestris/react-geo/issues/87. This PR should fix the `public-path` in `webpack.examples.config.js`.
Plz. review.
> Examples: Public-path for image and font resources

- .travis.yml
- enzyme.conf.js
- package-lock.json
- package.json
- src/Button/ToggleGroup/ToggleGroup.spec.jsx
- src/LayerTree/LayerTree.spec.jsx
This PR introduces React @ v16.0.0
It also adds the required updates for the following packages:
- `"react-dom": "16.0.0"`
- `"react-test-renderer": "16.0.0"`
… and makes use of:
`"enzyme-adapter-react-16": "1.0.0"` instead of `"enzyme-adapter-react-15": "1.0.0"`
There are currently two test failing. Maybe because of this bug:
https://github.com/airbnb/enzyme/issues/1163#issuecomment-332508771
> Update React to v16.0.0

- karma.conf.js
- src/Button/SimpleButton/SimpleButton.example.jsx
- webpack.examples.config.js
- webpack.production.config.js
This removes `unsafe:true` from `webpack.optimize.UglifyJsPlugin` as it causes bugs with react@16.
> Fix failing examples (production build) for react 16

- src/Panel/Panel/Panel.jsx
In version `v6.0.0` `dragHandlerClassName prop of  `Rnd` component has been renamed to `dragHandleClassName`. This PR transfers this to `react-geo`
Plz review.
> Renaming prop specifing selector of draggable component

- src/Button/SimpleButton/SimpleButton.example.jsx
- src/Button/ToggleButton/ToggleButton.example.jsx
- src/Button/ToggleGroup/ToggleGroup.example.jsx
- src/Field/NominatimSearch/NominatimSearch.example.jsx
- src/HigherOrderComponent/VisibleComponent/VisibleComponent.example.jsx
- src/LayerTree/LayerTree.example.jsx
- src/Legend/Legend.example.jsx
- src/Map/FloatingMapLogo/FloatingMapLogo.example.jsx
- src/Map/ScaleCombo/ScaleCombo.example.jsx
- src/Panel/Panel/Panel.example.jsx
- src/Panel/Titlebar/Titlebar.example.jsx
- src/Slider/LayerTransparencySlider.example.jsx
- src/Toolbar/Toolbar.example.jsx
- src/UserChip/UserChip.example.jsx
- tasks/build-examples.js
This updates the replacement of imports in the examples.
` //@react-geo@` is not needed anymore.
> Update replacement of imports to new namespace

- src/LayerTree/LayerTree.spec.jsx
This reenables some tests we disabled during the upgrade phase from react 16 to enzyme 3.
> Reenable LayerTree tests

- karma.conf.js
- src/HigherOrderComponent/MapProvider/MapProvider.jsx
- src/HigherOrderComponent/MapProvider/MapProvider.spec.jsx
- src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.jsx
- src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.spec.jsx
- src/Map/MapComponent/MapComponent.example.jsx
- src/Map/MapComponent/MapComponent.example.md
- src/Map/MapComponent/MapComponent.jsx
- src/Map/MapComponent/MapComponent.spec.jsx
- src/Panel/Panel/Panel.spec.jsx
- src/index.js
- webpack.examples.config.js
This introduces the HOCs `MapProvider` the `MappifiedComponent` (`mappify`) and the `MapComponent`.
Short explanation:
- The `MapProvider` adds a map to the context of the application.
- The `mappfiy` function grabs the map from the context and adds it as prop to the according component.
- The `MapComponent` just returns a div containing an OlMap.
It also includes an example of how to use these three new Components together.
We should check/modify our examples and tests to make use of the `MapProvider`.
Thx @dnlkoch and @ahennr for your support.
> Introduces MapProvider, mappify and MapComponent

- src/Util/CsrfUtil/CsrfUtil.js
- src/Util/CsrfUtil/CsrfUtil.spec.js
This PR adds a further function which returns a simple object containing CSRF header.
Plz review
> CSRFUtil: Return header as object

- tasks/build-examples.js
- webpack.examples.config.js
This adds a filter function to Metalsmith to avoid copying the spec-files to the examples folder.
> Adds filter-function to metalsmith

- package.json
With this, we no longer call the prepublish script after `npm i`
(which was already weird) but keep the logic for our publishing
(untested, TBH).
This reomves the following warnings:
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
See also https://docs.npmjs.com/misc/scripts
Please review.
> Change deprecated `prepublish` to `prepublishOnly`

- jest.config.js
- package.json
This PR suggests two changes:
**Ignore the build/`-directory when testing**
Locally for me the `npm test` failed with messages as follows.
FAIL  build/examples/Util/FeatureUtil.spec.js
● Test suite failed to run
Cannot find module 'expect.js' from 'FeatureUtil.spec.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
at Object.<anonymous> (build/examples/Util/FeatureUtil.spec.js:2:15)
I know that #231 will ensure that no spec files will be copied over, and this
is not a replacement for that PR.
**Don't always capture coverage** 
You can always reenable it with `npm test -- --coverage`, which is also done
during the `build`-script, which will ensure that CI will still have the
coverage.
> Ignor build-folder during test and make coverage optional

- src/CircleMenu/CircleMenu.spec.jsx
As the circlemenu tests fail randomly due to timing issues this introduces [Jest Faketimers](https://facebook.github.io/jest/docs/en/timer-mocks.html).
> Makes use of faketimers in circlemenu tests

- src/Field/ScaleCombo/ScaleCombo.jsx
- src/Field/ScaleCombo/ScaleCombo.spec.jsx
Value of a antd `Select` has to be of type String so we tranform it with `toString()`.
> ScaleCombo fixes

- src/CircleMenu/CircleMenu.example.jsx
- src/CircleMenu/CircleMenu.jsx
- src/CircleMenu/CircleMenu.less
- src/CircleMenu/CircleMenu.spec.jsx
- src/CircleMenu/CircleMenuItem/CircleMenuItem.less
This introduces the new `segmentAngles` property.
It allows to restrict the menuitems to appear in a specified segment of the circle:
> Introduces segments to CircleMenu

- dist/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.js
- dist/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.less
- dist/Container/AddWmsPanel/AddWmsPanel.js
- dist/Container/AddWmsPanel/AddWmsPanel.less
- dist/Util/CapabilitiesUtil/CapabilitiesUtil.js
- dist/index.js
- src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.jsx
- src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.less
- src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.spec.jsx
- src/Container/AddWmsPanel/AddWmsPanel.example.jsx
- src/Container/AddWmsPanel/AddWmsPanel.example.md
- src/Container/AddWmsPanel/AddWmsPanel.jsx
- src/Container/AddWmsPanel/AddWmsPanel.less
- src/Container/AddWmsPanel/AddWmsPanel.spec.jsx
- src/Util/CapabilitiesUtil/CapabilitiesUtil.js
- src/Util/CapabilitiesUtil/CapabilitiesUtil.spec.js
- src/index.js
- webpack.examples.config.js
* Container
* AddWmsPanel -- Panel containing a (checkable) list of AddWmsLayerEntry instances
* AddWmsLayerEntry -- Visual representation of layer entry parsed from capabilities document.
* adds an example which parses capabilities document of OWS terrestris
Plz review.
> Introduce AddWmsPanel

- src/Container/AddWmsPanel/AddWmsPanel.jsx
This introduces an optional prop `onSelectionChange` that can be used to provide a custom callback function for the selectionChange event.
> Add onSelectionChange prop

- src/Panel/Panel/Panel.jsx
- src/Panel/Panel/Panel.spec.jsx
This PR adds some prop functions (and tests) which are called as soon as the corresponding ones from react-rnd are called. 
This can be useful if width and height of a window are needed (e.g. for charting).
Plz review.
> Panel - resize prop functions

- dist/Container/AddWmsPanel/AddWmsPanel.js
- dist/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.js
- dist/HigherOrderComponent/MappifiedComponent/MappifiedComponent.js
- dist/Window/Window.js
- src/Container/AddWmsPanel/AddWmsPanel.jsx
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.jsx
- src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.jsx
- src/Window/Window.jsx
- src/Window/Window.spec.jsx
This PR adds warning which will be shown, if no valid `parentId` was provided by Window component instantiation and default value `parentId=app` doesnt' match.
If no valid parent was found, the component won't be rendered.
> Enhance parentId check for Window component

- package-lock.json
- src/Window/Window.jsx
- src/Window/Window.less
The `Window` component did only work in chrome properly. In other browsers (e.g. firefox) the wrapper div of the window has a `style="position: relative;"` element (which seems to come from the parent component [react-rnd](https://github.com/bokuweb/react-rnd)) and the window appeared below the viewport.
This is fixed by adding a `position: inherit !important;` to the `.react-geo-window-portal` CSS class. On top of that, this class will now correctly be set on the wrapper div (but not on the wrapped panel div as before).
> Make window compatible to other browsers than chrome

- package.json
Until now, when releasing with npm, only the tags were pushed to github, but the master had to be pushed manually.
With this change, the master will also be pushed within this process.
From the git docs:
<pre>
--tags
All refs under refs/tags are pushed, <b>in addition to refspecs explicitly listed</b> on the command line.
</pre>
> Also push master when releasing

- src/Util/CapabilitiesUtil/CapabilitiesUtil.js
- src/index.js
This adds the `nameField` parameter to the `getLayersFromWmsCapabilties` function.
It also adds the missing export of the `AddWmsLayerEntry`.
> Capabilites namefield

- package-lock.json
- src/HigherOrderComponent/MapProvider/MapProvider.jsx
- src/HigherOrderComponent/MapProvider/MapProvider.spec.jsx
This makes it easier for people who use `npm link`, where `instanceof` checks sometimes fail.
Also the code is easier to read. I was unsure about how I handle the tests, but this works locally for me. Looking forward to your review.
> Simplify map provider

- src/Panel/Panel/Panel.example.jsx
- src/Panel/Panel/Panel.jsx
- src/Panel/Titlebar/Titlebar.jsx
- src/Panel/Titlebar/Titlebar.less
- src/Panel/Titlebar/Titlebar.spec.jsx
- src/Window/Window.example.jsx
- src/Window/Window.jsx
This is a breaking change as it removes some props from `Panel`, `Titlebar` and `Window`:
- Removes closable prop from all three classes
- If you wan't to implement a close button just do it your self and pass it via the `tools` property.
- Removes collapsible prop from Titlebar
- This prop was not used as the `Panel` passes a CollapseButton if you configure it with `collapsible`
- Removes unused parent property from Titlebar and Panel
- Renames `compress…` props to `collapse…`
It also changes the way the `Panel` component calculates its height and the height of its body.
The old defaults for the props `height` (100) and `width` (100) are replaced with `'auto'` so the Panel will grow with its content, except you specify a specific height and width.
@terrestris/devs plz review (and test)
> Refactors Panel, Titlebar and Window

- src/Util/StringUtil/StringUtil.js
- src/Util/StringUtil/StringUtil.spec.js
This introduces the `stripHTMLTags` method to the `StringUtil`.
It removes the HTML-Tags and returns just the textual content. Compare the spec file.
> Introduces stripHTMLTags method to StringUtil

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Util/AnimateUtil/AnimateUtil.spec.js
This is a follow-up of #377 covering issues from https://github.com/terrestris/react-geo/issues/380.
Details:
- Introduced `style` property including the whole `ol.style.Style` object for the `DigitizeButton`. Currently this style will be used in the style function of the `digitizeLayer`. For the future it can be assigned to the singly drawn features to be able to manipulate its style e.g. via styler.
- Added `layerFilter` property to match only features of `digitizeLayer` in select/edit mode.
> Digitize tools enhancements

- package.json
`i18next` and `react-i18next` weren't is use and in my opinion `react-geo` should only expose all translatable contents as props so the real translation could take place in the application itself (e.g. by using `translate` provided by `react-i18next`).
> Remove unused i18n dependencies

- src/Button/ToggleGroup/ToggleGroup.jsx
This adds a check to the togglegroup render method to only apply the pressed state to children which are instances of `ToggleButton`.
Fixes #418
> Only apply pressed state to togglebuttons

- .gitignore
Add a basic `.gitignore`-file so we are able to work on the gh-pages branch locally.
> Add basic .gitignore file

- src/Grid/FeatureGrid/FeatureGrid.jsx
- src/Grid/FeatureGrid/FeatureGrid.spec.jsx
This introduces the `keyFunction` prop to the `FeatureGrid`. This allows to specify the way the rowkey is generated from the feature.
The default function is set to: `feature => feature.ol_uid`. Which makes this PR an API-breaking change. The previous logic was to just take the row index.
We discovered during project development, that a more precise id would be useful.
> Introduces the keyFunction prop to the FeatureGrid

- src/Grid/FeatureGrid/FeatureGrid.jsx
- src/Grid/FeatureGrid/FeatureGrid.spec.jsx
- src/Grid/FeatureGrid/FeatureGridWfs.example.jsx
This modifies the way of how the `featureStyle` prop is applied.
Currently the `featureStyle` is applied to every feature separately.
This PR changes the implementation so that the style is applied to the layer and not to the feature itself.
The advantage is, that you can have the feature in an existing vectorlayer overwriting its style there.
> Modifies implementation of featurestyle prop of FeatureGrid

- src/Grid/FeatureGrid/FeatureGrid.jsx
* use kebabCase for row keys
* If not `ol_uid` is used as row key (e.g. by using `keyFunction` prop with `keyFunction={f => f.getId()}` this can lead to errornous row class names that contain irregular characters like `.`. In order to prevent this, keys are [`"kebabCased"`](https://lodash.com/docs/4.17.5#kebabCase).
* enable rowClassName prop being a function as well
> Feature grid: rowClassName as function and CSS key fixes

- src/Legend/Legend.jsx
Render LegendGraphic again when props have changed
If the props of a Legend change, it will now get requested again.
Usecase: passing a dynamic `extraParam` to the legend like the `scale` parameter will now be handled correctly. Before, the legend was only rendered once and never again.
> Render LegendGraphic again when props have changed

- src/Button/ToggleButton/ToggleButton.jsx
The `ToggleButton` didn't execute a passed `onToggle` handler if in a `ToggleGroup`. With this PR he does again.
This should fix the `Digitizebutton` examples.
> Fixes bug in ToggleButton

- src/Button/DigitizeButton/DigitizeButton.jsx
This adds new props to the `DigitizeButton`:
- `OnDrawStart`: Optional listener function for the `drawstart` event of the [DrawInteraction](http://openlayers.org/en/latest/apidoc/ol.interaction.Draw.html)
- `OnDrawEnd`: Optional listener function for the `drawend` event of the [DrawInteraction](http://openlayers.org/en/latest/apidoc/ol.interaction.Draw.html)
> Adds props for 'onDrawStart' and 'onDrawEnd' listeners to DigitizeButton

- assets/TestCoords.js
- src/Util/GeometryUtil/GeometryUtil.js
- src/Util/GeometryUtil/GeometryUtil.spec.js
This PR adds support of Multi-Geometries (e.g. `MultiPolygon`)  as input  of `mergeGeometries` in `GeometryUtil`.
> GeometryUtil - support merge of MultiGeometry

- src/Util/GeometryUtil/GeometryUtil.js
- src/Util/GeometryUtil/GeometryUtil.spec.js
This introduces separateGeoemtries method to GeometryUtil. To split one or many "MultiGeometries".
The methods accepts a single or an Array of Geometries and/or MultiGeometries and returns an array of single Geometries.
Closes #483
> Introduces separateGeometries method to GeometryUtil

- src/Util/AnimateUtil/AnimateUtil.js
If the style given to the `moveFeature` method was null, an error occured in the animation and it never stoped translating the feature in the given direction.
This introduces two small checks to avoid this.
> Fixes bug in moveFeature method of AnimateUtil

- src/Util/MapUtil/MapUtil.js
This clarifies the description of `MapUtil`'s `getLayerByName()` method.
> Update method description

- src/Util/GeometryUtil/GeometryUtil.js
This removes 'Multi' from geomType comparison in `GeometryUtil.mergeGeomtries` to allow merging e.g. `MultiPolygon` with `Polygon`.
> Remove 'Multi' from geomType comparison in `mergeGeomtries`

- src/Button/ZoomInButton/ZoomInButton.example.jsx
- src/Button/ZoomInButton/ZoomInButton.jsx
- src/Button/ZoomInButton/ZoomInButton.spec.jsx
- src/Button/ZoomOutButton/ZoomOutButton.example.jsx
- src/Button/ZoomOutButton/ZoomOutButton.jsx
- src/Button/ZoomOutButton/ZoomOutButton.spec.jsx
- src/Button/ZoomToExtentButton/ZoomToExtentButton.example.jsx
- src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx
- src/Button/ZoomToExtentButton/ZoomToExtentButton.spec.jsx
- src/Util/TestUtil.js
This PR suggests to change the `ZoomInButton`, `ZoomOutButton` and `ZoomToExtentButton` to animate the view when zomming / fiting the extent by default.
One can still configure each component to not animate at all. The existing tests and examples have been updated to reflect these changes.
The `ZoomToExtentButton` class, test and example have been cleaned up. 
Some uneeded TestUtil functions have been removed. 
A future enhancement should factor out common code in a shared class. 
Fixes #516
> Use animations by default when zooming

- src/Slider/MultiLayerSlider/MultiLayerSlider.jsx
This fixes the labels of the MultiLayerSlider, as the `marks` property does expect an object and not a function.
> Fixup broken labels in MultiLayerSlider

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/DigitizeButton/DigitizeButton.spec.jsx
This PR renames the prop `style` to `drawStyle` since it is reserved for CSS inline-styles. Furthermore, a test has been added checking that passed style property to wrapped `ToggleButton`.
See also last point in #475 .
> DigitizeButton - rename style prop

- src/Field/WfsSearch/WfsSearch.example.md
- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
- src/index.js
This introduces the `WfsSearch`.
> Introduces WfsSearch

- src/Button/ZoomButton/ZoomButton.jsx
- src/Button/ZoomButton/ZoomButton.spec.jsx
This fixes two bugs with the `ZoomButton`:
* Multiple fast clicks on a `ZoomButton` could mess up the animation, because already running animations would not be canceled
* If you configured the `ZoomButton` with a map that did not have a view (yet), clicking the button would throw an exception 
Also zooming now uses the same defaults for animations as the standard OpenLayers controls (`easeOut` animation an the duration is `250ms`)
Please review.
> Faster & less error-prone zooming

- src/Field/WfsSearch/WfsSearch.example.md
- src/Field/WfsSearch/WfsSearch.jsx
This makes adds the `optionLabelProp` to be more flexible. Although it is an antd prop we have to introduce it as a prop because we set a default for it.
The default for the `renderOption` prop has been adapted to the changes.
Breaking change:
Modifies the `searchAttributes` to be receive an object instead of an array. To be more precise doing the WFS-GetFeature request. 
Thx for support @hwbllmnn
> Changes to WfsSearch

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx
- src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.spec.jsx
- src/Container/AddWmsPanel/AddWmsPanel.spec.jsx
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.example.md
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.jsx
- src/Field/NominatimSearch/NominatimSearch.jsx
- src/Field/WfsSearch/WfsSearch.example.md
- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
- src/Legend/Legend.spec.jsx
- src/Panel/Panel/Panel.example.md
- src/Util/FeatureUtil/FeatureUtil.spec.js
- src/Util/MapUtil/MapUtil.spec.js
- src/Util/MeasureUtil/MeasureUtil.js
- src/Util/StringUtil/StringUtil.js
- src/Util/StringUtil/StringUtil.spec.js
- src/Util/UrlUtil/UrlUtil.js
This replaces 'http'-URLs with 'https'-ones where possible and useful.
This also fixes the online examples like the WFS search which wouldn't work on the hosted HTTPS page as it tried to load content from a HTTP resource.
Please review.
> Less HTTP, more HTTPS

- .vscode/launch.json
This fixes the `Debug Jest Tests` script for vscode by adding a port.
Test will now also run in an external terminal and in watchmode.
> Fix test debugging command for vscode

- src/Field/WfsSearch/WfsSearch.spec.jsx
If this is not included local tests for `WfsSearch` run into an error
```
Ran 100000 timers, and there are still more! Assuming we've hit an infinite
recursion and bailing out...
```
Using this fix, Jest will wait until the `done` callback is called before finishing the test.
> Use `jest.DoneCallback` in test of WfsSearch

- src/Field/WfsSearch/WfsSearch.spec.jsx
This PR increases the timeout used in test of `onSelect` (`WfsSearch`) to 500ms + 10ms (as in test of CircleMenu)
> Increase timeout in onSelect test of WfsSearch

- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
This fixes issue #621 , making sure only the most recent search request data is used. Thanks @KaiVolland !
> make sure only the most recent request data is used

- src/Field/WfsSearch/WfsSearch.jsx
This PR fixes searching number fields via WFS. This is still far from perfect. You can configure the WFS search now with attribute details, which allows you to control how filters are created. `matchCase` can be used to control the corresponding filter attribute, `exactSearch` will make the code check for attributes of type `number` and `int` and skip the filter completely if the search term contains non numeric characters.
We should really think about doing a solr or elastic search backend in order to get better results.
> Fix searching number fields

- src/Button/GeoLocationButton/GeoLocationButton.jsx
The marker of the geolocation button would sometimes not be shown if the location isn't changed. This PR makes sure the marker has the proper `src` in all cases it is created.
> Fix vanishing marker

- src/Panel/Titlebar/Titlebar.less
This fixes the styling of the `Titelbar` as an update of Ant Design added a default padding to the ant-modal-header.
Before:
After:
> Fixes titlebar style

- jest.config.js
Previously we would collect coverage information from the `assets/`- and `jest/`- directories, which should not matter to us. I belive this will bring down coverage a bit, but the then reported value is a bit closer to the reality.
Update: as expected coverage went down quite a bit (`-6.8 %`).
> Collect coverage from src directory only

- jest.config.js
A better configuration for coverage collection. The previous configuration excluded `*.js` files (and only kept `*.jsx`) and erroneously included at least one example.
The [last build](https://coveralls.io/builds/16880847) had coverage for 40 files, the [current one](https://coveralls.io/builds/16883356) has coverage for 56 files (see all those with the small pluss sign for those that we previously missed).
> Better configuration for coverage collection

- src/Field/ScaleCombo/ScaleCombo.jsx
- src/Field/ScaleCombo/ScaleCombo.spec.jsx
This PR adds a prop `resolutionsFilter` to `ScaleCombo` in order to filter resolutions for which no `Select.Option` items will be created in the combo.
> Resolutions filter for scale combo

- README.md
We are no longer erroneously flagged as having a vulnerable transitive dependency by david-dm. We can therefor remove the footnote with more information that clarified this to readers.
This effectively reverts the relevant parts of commit 9b0c7c801785c4777e4561851f22554257c6f2f9 introduced in #618.
Please review.
> Remove unneeded info wrt the non-existant vulnerability

- src/Field/WfsSearch/WfsSearch.jsx
- src/Util/WfsFilterUtil/WfsFilterUtil.js
- src/Util/WfsFilterUtil/WfsFilterUtil.spec.js
- src/index.js
Extracted `createWfsFilter` method from `WfsSearch` class and moved it to the new utility class `WfsFilterUtil` to make it reusable in other projects.
> Extract createWfsFilter method to WfsFilterUtil

- package.json
- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/MeasureButton/MeasureButton.jsx
- src/Button/ToggleButton/ToggleButton.jsx
- src/Button/ToggleGroup/ToggleGroup.jsx
- src/Field/ScaleCombo/ScaleCombo.jsx
- src/Grid/AgFeatureGrid/AgFeatureGrid.jsx
- src/Grid/FeatureGrid/FeatureGrid.jsx
- src/Grid/PropertyGrid/PropertyGrid.jsx
- src/LayerTree/LayerTree.jsx
- src/Legend/Legend.jsx
This fixes the usage of all deprecated ReactJS lifecycle methods (see #648) and updates the `eslint-plugin-react` to the current release (closes #647).
> Remove usage of deprecated lifecycle methods

- src/Util/WfsFilterUtil/WfsFilterUtil.js
- src/Util/WfsFilterUtil/WfsFilterUtil.spec.js
Follow-up of #662 
* Added some more additional checks to ensure that `attributeDetails` object is provided and has expected keys (e.g. `type`, `exactSearch` or `matchCase`)
* Enhanced fallback return value if no `attributeDetails` is given.
> Get smarter by `attributeDetails` object access in `WfsFilterUtil`

- src/Util/MapUtil/MapUtil.js
- src/Util/UrlUtil/UrlUtil.js
Internet explorer does not support .find without polyfills, switching to .filter()[0] produces the same result for the function getLayerByName in MapUtil.js
> Changed find to filter to support IE

- src/Field/NominatimSearch/NominatimSearch.jsx
This removes the wrong configured `optionLabelProp` from the NominatimSearch. It uses the default value (the children of the select option) as display value now.
It also includes some minor changes to the docs as these causes some warnings from react-dom.
> Removes static broken `optionLabelProp` from NominatimSearch

- src/Util/MeasureUtil/MeasureUtil.js
- src/Util/MeasureUtil/MeasureUtil.spec.js
This adds `getLength` and `getArea` mehtods to the `MeasureUtil`.
The methods `formatLength` and `formatArea` reuse them.
> Adds getLength and getArea methods to MeasureUtil

- src/Button/MeasureButton/MeasureButton.jsx
- src/Button/MeasureButton/MeasureButton.spec.jsx
This PR handles several issues with the measure buttons.
Measurements of polygons were not displayed at all on mobile devices, as the tooltips have only been set in the `pointerMoveHandler` function. This has been changed and renamed to make more sense and to get it work on mobiles.
Additionally, a `showHelpTooltip` flag has been introduced to switch the tooltips of, which is especially useful for mobile devices.
> Fixup measure button, better mobile support

- src/Util/ObjectUtil/ObjectUtil.js
- src/Util/ObjectUtil/ObjectUtil.spec.js
This adds the `getPathByKeyValue` method to the `ObjectUtil`, that may be used to returns the dot delimited path of a given object by the given key-value pair.
> Add getPathByKeyValue to ObjectUtil

- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
This applies some updates to the `WfsSearch` component:
* Fix prop validation for `attributeDetails`.
* Don't override component's `onChange` prop.
* Don't use `optionLabelProp`, introduce `displayValue` instead.
* Update the default `renderOption`function to include the newly introduced `displayValue` prop.
* Fix async test to return a `Promise`.
> Several updates for the WfsSearch

- src/Util/ObjectUtil/ObjectUtil.js
- src/Util/ObjectUtil/ObjectUtil.spec.js
This fixes the newly introduced `getPathByKeyValue()` to only start the recursion if the given key is a plain object. It also updates the tests.
> Fix getPathByKeyValue to check for plain objects in recursion

- src/Button/DigitizeButton/DigitizeButton.jsx
This adds even more optional listener props to the `DigitzeButton` and removes any interaction on unmount.
> Digitize button listener props

- src/Slider/TimeSlider.jsx
- src/Slider/TimeSlider.spec.jsx
This introduces the `convertMarks` method to the `TimeSlider`.
It is needed to support the `marks` property of the antd `Slider`.
> Introduces convertMarks method

- src/Button/ToggleButton/ToggleButton.jsx
- src/Button/ToggleGroup/ToggleGroup.jsx
This fixes 2 things:
1.) The initial behaviour of a ToggleButton, when it was given a prop `pressed=true` was not handled correctly. We now call the belonging `onToggle` method to correctly initialize the button
2.) The `pressed` property of a ToggleButton now gets passed through, if it exists
> Fixup ToggleGroup and Buttons

- src/LayerTree/LayerTree.jsx
- src/LayerTree/LayerTree.spec.jsx
This PR enables the LayerTree to also reflect changes in the tree when the ol.Collection of the LayerGroup is replaced. E.g:
map.getLayerGroup().setLayers(new OlCollection([subLayer]));
did not trigger any change before, but now it does handle it correctly
> Handle changes in layerGroups collection in layertree

- src/Field/WfsSearch/WfsSearch.jsx
This prevents the crash of the `WfsSeach` component when no request parameters exists. 
When an empty array is passed to the `featureType` property of the `WfsSeach` component it will cause it to crash since the request will be undefined and can not be stringified.
@terrestris/devs please review.
> Adds extra check for WfsSeach Component 

- package-lock.json.4212429241
- src/Container/AddWmsPanel/AddWmsPanel.example.md
- src/Panel/Panel/Panel.jsx
- src/Window/Window.jsx
This excludes `titleBarHeight` and `collapseTooltip` from being passed to the `Rnd` component in `Panel`.
This also fixes the syntax of the `dragHandleClassName` prop of the `Rnd` component. It has been changed in `react-rnd@8.0.2` to omit the leading dot.
> Exclude titleBarHeight and collapseTooltip from passed props

- src/Button/ToggleGroup/ToggleGroup.jsx
This fixes the `ToggleGroup` (what a classy).
For clarification:
The pressed-state of a `ToggleButton` is determined by its `pressed` prop. Which is `false` per default.
The current concept of the `ToggleGroup` is to set this via the `selectedName` which matches the `name` property of a `ToggleButton`.
->> As this concept doesn't seem to be very intuitive we should change it.
So the old line 165 was always true and the `ToggleButtons` never changed their state… Compare broken example.
> [ToggleGroup] Revert pressed prop priority handling

- src/Button/DigitizeButton/DigitizeButton.jsx
By this PR, the `getDigitizeStyleFunction` function will be applied to the `digitizeLayer` of the `DigitizeButton` is toggled. Herewith, the current set `drawStyle` is always used to draw vector features.
Plz review
> Set style function with current draw style if pressed

- src/Button/SimpleButton/SimpleButton.jsx
- src/Button/ToggleButton/ToggleButton.jsx
This adds the prop `tooltipProps` to the button base classes, that can be used to pass [any valid](https://ant.design/components/tooltip/) `Tooltip` props to them.
> Add tooltipProps prop to pass any valid antd tooltip prop

- jest.config.js
This sets the `testURL` in the jest config to a non-default value to prevent the error
```
SecurityError: localStorage is not available for opaque origins
```
See facebook/jest#6766.
> Set testURL in jest config

- src/Panel/Panel/Panel.jsx
Fixes #805 : Removes the unused prop 'closable' from Panel.jsx
> Remove unused prop closable from Panel

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/DigitizeButton/DigitizeButton.spec.jsx
- src/Button/MeasureButton/MeasureButton.jsx
- src/Button/MeasureButton/MeasureButton.spec.jsx
This PR adds a further props `onToogle` as function that will be called in the private `onToggle` of `DigitizeButton` and `MeasureButton`
> Add onToggle as prop for DigitizeButton and MeasureButton

- src/Panel/Panel/Panel.jsx
- src/Window/Window.example.md
Follow up of #804.
Fixes bug with cloning of `tools` prop introduced in #804:
`cloneDeep` method of `lodash` library seems to not work properly with cloning of react nodes, so an alternative solution by using of `React.cloneElement()` method was prefered.
Additionally got rid of some hard coded values by computing of default panel position and fixed wrong positioned windows in examples.
BTW, determination of default panel/window position seems to be buggy since last major update of `rnd` package, so fixing of window examples should be temporary solution only --> s. #812 
> Div panel fixes

- src/LayerTree/LayerTree.jsx
- src/LayerTree/LayerTree.spec.jsx
The LayerTree does now update when the nodeTitleRenderer prop has changed. This is needed for example when you want to dynamically show/ hide the node title (or with image/ without image).
Please review also if the test makes sense like this.
> make LayerTree update when prop nodeTitleRenderer has changed

- src/Grid/AgFeatureGrid/AgFeatureGrid.jsx
When using AgFeatureGrid's `onRowClick` property, two parameters will be added to the callback function: `row` and `feature`, where `row` equals the original event's `event.data` property (see code below). This PR adds the original event as a whole as third property, so we don't have a loss of information here. This could be useful for instance to allow editing of specific cells but still keep the onRowClick event active.
resolves https://github.com/terrestris/react-geo/issues/846
> AgFeatureGrid add original event to onRowClick callback

- package.json
- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearchInput/WfsSearchInput.example.md
- src/Field/WfsSearchInput/WfsSearchInput.jsx
- src/Field/WfsSearchInput/WfsSearchInput.spec.jsx
- src/index.js
Introduced `WfsSearchInput` component which can be actually regarded as an alternative to already existing `WfsSearch` component which depends on `ant` `Select``component.
The new component based on `ant` `Input` field only and shows by default no output on successfully fetched features. The way how retrieved features should be represented is determined from user and can be passed with  `onFetchSuccess` function in prop.
Additionally:
* fixed existing `WfsSearch` component by replacing of deprecated `mode=combobox` property of `Select` by `<AutoComplete>`
* Passing an optional callback function `onBeforeSearch` to be able to manipulate user input before search starts
* Moved `getCombinedRequests` function to `ol-util` 
Note: https://github.com/terrestris/ol-util/pull/30 must be merged and …
> Introduce `WfsSearchInput` component

- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
- src/Field/WfsSearchInput/WfsSearchInput.jsx
- src/Field/WfsSearchInput/WfsSearchInput.spec.jsx
Get rid of timeout function and use `lodash/debounce` function instead to delay invoking of `doSearch` method call for `WfsSearch` and `WfsSearchInput` component.
Also addresses notes mentioned by @dkoch in #878.
> Use lodash/debounce for delayed function calls

- src/Button/DigitizeButton/DigitizeButton.jsx
The digitizeButton was lacking a callback function after clicking on OK and CANCEL in the modal that pops up when adding a label. The properties `onModalLabelOk` and `onModalLabelCancel` now implement this.
`onModalLabelOk` returns the added feature as well as the text content of the input field in the modal.
`onModalLabelCancel` does not return anything.
Edit: Added `onModalLabelCancel` to desription
> Add callback props onModalLabelOk and onModalLabelCancel to DigitizeButton

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/HigherOrderComponent/LoadifiedComponent/LoadifiedComponent.jsx
The digitizeButton was lacking a callback function after clicking on OK and CANCEL in the modal that pops up when adding a label. The properties `onModalLabelOk` and `onModalLabelCancel` now implement this.
`onModalLabelOk` returns the added feature as well as the text content of the input field in the modal.
`onModalLabelCancel` does not return anything.
> Add callback props onModalLabelOk and onModalLabelCancel to DigitizeButton for ol4

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx
- src/Field/WfsSearch/WfsSearch.jsx
The comments in 3 modules refer to OpenLayers documentation in /latest/apidoc/. OL has changed the format of the URL, and this PR updates the comments to the current format.
Note that in three cases in DigitizeButton.jsx the events mentioned in the comments are (no longer?) referred to on the OL documentation page. This might indicate the comment itself needs updating, as well as the URL - but I do not know enough to decide.
The relevant interactions and events are:
- Modify.Event : modifystart and modifyend events
- Translate.Event: translatestart, translateend and translating events
- Select.Event: select event
> Change references to OL documentation in comments to the latest format

- src/Button/ZoomButton/ZoomButton.jsx
We should always cancel any pending/running animations, regardless of whether we will change the zoom in an animated way or not.
> Always cancel animation

- .eslint-common.js
This removes a warning when linting by configuring the react version for an eslint plugin
Before:
```
$ npm run lint:src
> @terrestris/react-geo@10.3.0 lint:src /home/jansen/code/react-geo
> eslint -c .eslint-src.js --ext js,jsx,html src/
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.
```
After:
```
$ npm run lint:src
> @terrestris/react-geo@10.3.0 lint:src /home/jansen/code/react-geo
> eslint -c .eslint-src.js --ext js,jsx,html src/
```
> Specify react version for linter

- package.json
This updates several dependencies.
* `whatwg-fetch` from `2.0.4` to `3.0.0` (used by `jest`, testing only, breaking changes shouldn't affect us) 
* `file-loader` from `1.1.11` to `2.0.0` (the breaking change there is the requirement for `"node": ">=6.9.0 < 7.0.0 || >= 8.9.0"`, even though we do not specify it, we require Node > 8 already, e.g. on Travis.) 
* `eslint` from `5.5.0` to `5.6.0` (feature update)
* `jest` from `22.4.3` to `23.6.0` (unproblematic in my local setup)
> Update several dependencies

- src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx
We should cancel pending/running animations prior to starting new ones. Otherwise erroneous behavior can be expected.
> Before setting the extent, better cancel any animations

- src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx
This addresses two comments by @dnlkoch on #897:
* Less strict PropTypes type for `fitOptions` (=> a feature, people cann now pass more options than before)
* A minor change in the documentation
Please review.
> Less strict PropTypes type & slightly enhanced docs

- src/Button/DigitizeButton/DigitizeButton.jsx
Title says it all. 
Possible use case: `styleFunction` of `ol.select.Interaction` doesn't take effect when selected feature already has style. The proposed callback function can be used to force setting of overriden select style.
ol4 compatible PR version can be found under https://github.com/terrestris/react-geo/pull/906.
> Provide optional callback prop `onFeatureSelect` to be used with `ol.interaction.Select` (ol5)

- src/Button/DigitizeButton/DigitizeButton.jsx
Possible use case: `styleFunction` of `ol.select.Interaction` doesn't take effect when selected feature already has style. The proposed callback function can be used to force setting of overriden select style.
> Provide optional callback prop `onFeatureSelect` to be used with `ol.interaction.Select` (ol4)

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/DigitizeButton/DigitizeButton.spec.jsx
* Use `ant` `Input.TextArea` instead of `Input` to enable multiline labels
* Set currently modifying label as value in label edit modal (previously value was always empty)
* Introduced new numerical prop `maxLabelLineLength` to determine if label should be divided into multiline label after provided threshold is exceeded
* Ensure that `onModalLabelOk` / `onModalLabelCancel` callback function will be called with updated values by moving them into `setState` callback
ol4 compatible PR version can be found under #908.
> Enhance label handling in `DigitizeButton` component (ol5)

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/DigitizeButton/DigitizeButton.spec.jsx
* Use `ant` `Input.TextArea` instead of `Input` to enable multiline labels
* Set currently modifying label as value in label edit modal (previously value was always empty)
* Introduced new numerical prop `maxLabelLineLength` to determine if label should be divided into multiline label after provided threshold is exceeded
* Ensure that `onModalLabelOk` / `onModalLabelCancel` callback function will be called with updated values by moving them into `setState` callback
> Enhance label handling in `DigitizeButton` component (ol4)

- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/MeasureButton/MeasureButton.jsx
- src/Button/ToggleButton/ToggleButton.jsx
- src/Button/ToggleGroup/ToggleGroup.jsx
- src/Container/AddWmsPanel/AddWmsPanel.jsx
- src/Field/ScaleCombo/ScaleCombo.jsx
- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearchInput/WfsSearchInput.jsx
- src/Grid/AgFeatureGrid/AgFeatureGrid.jsx
- src/Grid/AgFeatureGrid/AgFeatureGrid.spec.jsx
- src/Grid/FeatureGrid/FeatureGrid.jsx
- src/Grid/PropertyGrid/PropertyGrid.jsx
- src/HigherOrderComponent/TimeLayerAware/TimeLayerAware.jsx
- src/LayerTree/LayerTree.jsx
- src/Legend/Legend.jsx
- src/Panel/Panel/Panel.jsx
- src/Panel/Titlebar/Titlebar.jsx
- src/Slider/TimeSlider.jsx
- src/Window/Window.jsx
Non-functional changes.
* Remove unneeded `*.js extension from `lodash` imports
* Import specific `lodash` functions instead of whole package for `ScaleCombo` class.
> `lodash` imports cleanup

- package.json
- src/Panel/Panel/Panel.jsx
For unknown reasons we had to reset greenkeeper for this repo (see [greenkeeper-initial PR](#938)). Due to the update of all dependencies, two issues were introduced and will be fixed with this PR:
* Downgrade `babel-loader` to 7.1.5 as were not compatible with Babel 7.
* Fix import for `rnd`.
> Fix greenkeeper initial

- src/Field/NominatimSearch/NominatimSearch.jsx
This introduces an `onClear`method to the `NominatimSearch` which can be passed as a prop.
> Introduces onClear prop to NominatimSearch

- src/LayerTreeNode/LayerTreeNode.jsx
- src/Map/MapComponent/MapComponent.jsx
This PR introduces `PureComponents` for `LayerTreeNode` and `MapContainer` component of react-geo so that implicitly a `shouldComponentUpdate` function is generated. 
See also https://github.com/terrestris/react-geo/issues/650
> Inherit LayerTreeNode and MapContainer from React.PureComponent

- src/LayerTree/LayerTree.jsx
Until now, `change:resolution` has been used to detect resolution changes. However, this has a drawback since it is fired as long the view is animating (see https://github.com/openlayers/openlayers/issues/7402). Since a "final" `change:resolution` after animation is not fired yet (see [here](https://github.com/openlayers/openlayers/issues/7409)) the `moveend` event of the map is used to detect changes in current map resolution.
As a consequence Layertree will me rendered less often.
> Rebuild tree nodes on moveend event of map if resolution changed

- src/LayerTree/LayerTree.jsx
Title says it all. Affected component: `LayerTree.jsx`
> A valid state object (or null) must be returned in getDerivedStateFromProps

- src/Button/GeoLocationButton/GeoLocationButton.jsx
This fixes a nasty error on the console as the prop isn't a valid button attribute.
> Don't pass trackingOptions prop to ToggleButton

- src/Grid/AgFeatureGrid/AgFeatureGrid.example.md
This removes some warnings in the `AgFeatureGrid` example by removing the usage of the outdated API.
> Remove warnings in AgFeatureGrid example

- src/Button/DigitizeButton/DigitizeButton.jsx
Fixes prop type check by replacing `oneOf` (literal comaprison) with `oneOfType` for property `drawStyle`
> Fixup prop type checking in DigitizeButton

- babel.config.js
- package.json
This replaces the outdated babel plugin `babel-plugin-transform-import-extension-jsx-to-js` with `babel-plugin-module-resolver`.
> Replace outdated babel plugin

- src/LayerTree/LayerTree.jsx
- src/LayerTreeNode/LayerTreeNode.jsx
This introduces a `onExpand` listener that calls `rebuildTreeNodes`, as expanding Trees with more the 1 level didn't work properly.
> Forces rebuildTreeNodes onExpand

- src/Panel/Panel/Panel.jsx
- src/Panel/Panel/Panel.spec.jsx
`Window` component  won't be autofocused on render. That leads to missing behaviour of `onEscape` function which can be optionally provided as prop (e.g. closing window on Escape didn't work anymore out of the box -> to get it work, user had to click manually into the window body firstly to set focus on component).
This PR fix the described issue, `onEscape` handler will be called now even if the Window component is not currently focused.
> Fix `onEscape` function call for Window component

- src/LayerTreeNode/LayerTreeNode.jsx
This adds an extra CSS class to `LayerTreeNodes` to differentiate between folders and leafs.
> Adds leaf/folder css-class to TreeNode

- src/Panel/Panel/Panel.jsx
Tiny fix to ensure that `Escape` key will also be matched while using IE.
> Fix escape key for IE

- src/Field/NominatimSearch/NominatimSearch.jsx
- src/Field/NominatimSearch/NominatimSearch.spec.jsx
This fixes the `onMenuItemSelected` handler of the `NominatimSearch`, which is currently broken due to a change in the response of the API. 
The property `place_id` has been changed from string to a number, which causes a comparison to fail. This has been fixed by comparing both values stringified with `toString()`
> Fixup nominatim search by comparing strings

- src/Field/WfsSearch/WfsSearch.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
This adds the prop `idProperty` to the `WfsSearch` to define a custom id property for the requested feature types.
See #1097.
> Customizable id property in WfsSearch

- src/Panel/Panel/Panel.example.md
- src/Panel/Panel/Panel.jsx
Introduces `collapsed` property on `Panel` to be able to decide whether the component should be rendered collapsed initially or not.
Also provides an appropriate example.
Resolves #1102 
> Make `collapsed` property of Panel component configurable

- src/Button/ZoomButton/ZoomButton.jsx
This PR adds `map` to prop destructuring in `render` of `ZoomButton`. Otherwise, the map will be passed as object string to antd button.
> ZoomButton: Destructure map prop in render

- src/Container/AddWmsPanel/AddWmsPanel.example.md
Fix example for `AddWmsPanel` after [@terrestris/ol-util](https://github.com/terrestris/ol-util/) major upgrade caused by https://github.com/terrestris/ol-util/pull/86
> Fix method name after @terrestris/ol-util major upgrade

- jest/setup.js
- package.json
- src/Button/DigitizeButton/DigitizeButton.spec.jsx
- src/Button/MeasureButton/MeasureButton.spec.jsx
- src/CircleMenu/CircleMenu.spec.jsx
- src/CircleMenu/CircleMenuItem/CircleMenuItem.spec.jsx
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.spec.jsx
- src/Field/NominatimSearch/NominatimSearch.spec.jsx
- src/Field/ScaleCombo/ScaleCombo.spec.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
- src/Field/WfsSearchInput/WfsSearchInput.spec.jsx
- src/Grid/AgFeatureGrid/AgFeatureGrid.spec.jsx
- src/Grid/FeatureGrid/FeatureGrid.spec.jsx
- src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.spec.jsx
- src/LayerTree/LayerTree.spec.jsx
- src/Panel/Panel/Panel.spec.jsx
- src/Window/Window.spec.jsx
This replaces the `canvas-prebuilt` with the `canvas` dependency. 
In addition all calls to `jest.resetAllMocks()` and `jest.restoreAllMocks()` are removed as they would also restore the newly introduced `jest-canvas-mock` functionality. Calls to `mockFn.mockReset()` are removed as well, because it will be called by `mockFn.mockRestore()` anyways (see [here](https://jestjs.io/docs/en/mock-function-api.html#mockfnmockrestore)).
Fixes #1118.
>  Replace canvas-prebuilt with canvas

- .ci/update-gh-pages.sh
This fixes the update of the `gh-pages` branch to create a versioned snapshot of the styleguide if a tag has beed created.
> Update gh-pages branch if tag has been created

- src/Panel/Panel/Panel.example.md
Fix unsupported style property `padding-right` to get rid of warning in example for panel component:
`Warning: Unsupported style property padding-right. Did you mean paddingRight?`
> Fix unsupported style property padding-right

- .ci/update-gh-pages.sh
This modifies the `update-gh-pages.sh` to also copy the docs to `latest` when a tag is pushed.
Previously pushing tags only [removed](https://github.com/terrestris/react-geo/blob/master/.ci/update-gh-pages.sh#L55) the `latest` folder but didn't copy the new docs.
Thx for the hint @cwillmes
> Copy docs to latest for tags too

- src/Map/MapComponent/MapComponent.jsx
Unsets the target of the `ol.Map` if the `MapComponent` will unmount. This is needed, if the `MapComponent` runs through the lifecycle multiple times, e.g. in a routable application, as the map's target won't be set if the target has been set before.
Fixes #1216.
> Unset the map's target on unmount

- package-lock.json
- package.json
- src/LayerTreeNode/LayerTreeNode.spec.jsx
This updates `antd` to the latest version and fixes the failing `LayerTreeNode` test. It can't be rendered standalone without a context `Provider` (the `Tree` component) component anymore.
Closes #1220.
> Update antd to the latest version

- package-lock.json
- package.json
- src/Button/DigitizeButton/DigitizeButton.jsx
- src/Button/DigitizeButton/DigitizeButton.spec.jsx
- src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx
- src/Field/WfsSearch/WfsSearch.spec.jsx
- src/Util/TestUtil.js
Upgrade to `ol` version 6.x considering [release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0) for release 6.0.0.
Depends on https://github.com/terrestris/ol-util/pull/147 and needs https://github.com/terrestris/ol-util/ release before merge.
> Upgrade to OpenLayers v6 

- .travis.yml
This removes node 8 from travis as [its end](https://github.com/nodejs/Release#nodejs-release-working-group) is near.
This will speed up the CI time.
> Removes node 8 from travis due to its end

- package.json
- src/UserChip/UserChip.tsx
- styleguide.config.js
- tsconfig.json
- webpack.common.config.js
This reintroduces the usage of `babel` for the transpilation as `tsc` was not capbale of loading the correct style files.
This includes some changes to tsconfig, too.
It also fixes some issues with the `UserChip`.
> Use babel for transpilation of typescript

- package-lock.json
- src/HigherOrderComponent/LoadifiedComponent/LoadifiedComponent.tsx
- src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.tsx
- src/HigherOrderComponent/VisibleComponent/VisibleComponent.tsx
As functional components can't have refs a Warning is thrown when using the HOC with these.
To avoid this a check is added to the HOCs.
> Avoids adding ref to wrapped functional components

- src/HigherOrderComponent/LoadifiedComponent/LoadifiedComponent.spec.tsx
- src/HigherOrderComponent/LoadifiedComponent/LoadifiedComponent.tsx
- src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.spec.tsx
- src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.tsx
- src/HigherOrderComponent/VisibleComponent/VisibleComponent.spec.tsx
- src/HigherOrderComponent/VisibleComponent/VisibleComponent.tsx
- src/Util/TestUtil.tsx
Removes the `withRef` option in some HOCs. It's not clear (except for the tests) why it's needed overall and it isn't working with function components or already wrapped components anyway. One should use `React.forwardRef()` instead if really needed.
Please review @KaiVolland.
> Remove with withRef option in high order components

- jest.config.js
This fixes the coverage collection. For some strange reason the previous pattern didn't work anymore. Maybe a bug in jest?
Be aware that the ugly :x: is not an indicator for a failing CI but that the coverage collection works again.
> Fixes coverage collection

- src/LayerSwitcher/LayerSwitcher.example.md
- src/LayerSwitcher/LayerSwitcher.less
- src/LayerSwitcher/LayerSwitcher.spec.tsx
- src/LayerSwitcher/LayerSwitcher.tsx
- src/Util/TestUtil.tsx
- src/index.ts
- styleguide.config.js
This introduces the `LayerSwitcher`.
A component designed to be used for switching between two (or more) backgroundlayers.
The view of the `LayerSwitcher` is synched with the maps view.
> Introduces LayerSwitcher

- jest.config.js
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.example.md
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.less
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.spec.tsx
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.tsx
- src/Slider/TimeSlider/TimeSlider.tsx
- tslint.json
This merges the existing `TimeSlider` and `TimeLayerAware` components into the new panel component `TimeLayerSliderPanel`.
Some points are still open:
Maybe another rect-geo @terrestris/devs can help me out here soon.
> Introduces the TimeLayerSliderPanel for WMS-T layer

- src/CoordinateInfo/CoordinateInfo.tsx
Don't bundle requests in the `CoordinateInfo` component, the ol format parser can't handle different feature types in a single response.
> Fix for different feature types in a single response

- package-lock.json
This reverts terrestris/react-geo#1366 since the build is failing afterwards. See [here](https://github.com/openlayers/openlayers/issues/10871) for details why.
> Revert "Bump ol from 6.2.1 to 6.3.0"

- src/Button/MeasureButton/MeasureButton.tsx
Fixes an error for type definition of `olCoordinate`.  
`olCoordinate` is a module and not a type.
> Fixes a type definition error for OlCoordinate (master v13)

- src/Button/MeasureButton/MeasureButton.tsx
Fixes an error for type definition of `olCoordinate`.  
`olCoordinate` is a module and not a type.  
This is a request to update the current master (v14)!
> Fixes a type definition error for OlCoordinate (master v14)

- styleguide.config.js
Documentation website was taking too long to load, because it was loading all the examples on start. Added pagePerSection on `styleguide.config` to avoid this scenario.
Fixes Issue? #697 
Examples added? No need to
Tests added? No need to
Docs added? No need to
Would a screenshot be helpful? see below
Do you want to mention someone? @weskamm , @marcjansen , @dnlkoch
> added pagePerSection and sectionDepth to styleguide.config.js

- src/Button/DigitizeButton/DigitizeButton.spec.tsx
- src/Button/DigitizeButton/DigitizeButton.tsx
- src/Util/TestUtil.tsx
This suggests to create all required interactions by the `DigitizeButton` on mount and to toggle the active state instead of recreating them on toggle.
> DigitizeButton interaction handling

- src/Button/ToggleGroup/ToggleGroup.tsx
react-geo was failing if child was null. This fixes this issue.
> handle child null case

- src/Hook/useMap.example.md
This updates the `useMap` hook example to render a second component using the same map.
> Add another component to the example using the same map

- src/Button/ToggleButton/ToggleButton.tsx
- src/Button/ToggleGroup/ToggleGroup.tsx
DOCUMENTATION
`ToggleButton` has a property called `pressed` that is overridden by the property `selectedName` from `ToogleGroup`. This appears to cause some confusion on some users, so a note to the documentation has been added.
Fixes Issue? #1710 
Examples added? No (not needed)
Tests added? No (not needed)
Docs added? Yes
Would a screenshot be helpful? No
> Added notes to documentation on ToogleGroup and ToogleButton

- src/Button/ZoomToExtentButton/ZoomToExtentButton.example.md
- src/Button/ZoomToExtentButton/ZoomToExtentButton.spec.tsx
- src/Button/ZoomToExtentButton/ZoomToExtentButton.tsx
- Adds option to define the extent via _center_ and _zoom_
- Change _extent_ to be an optional prop, same as _center_ and _zoom_
- Adds notification if none of the necessary props are provided
Background: Since a fixed extent is mostly dependant on screen ratio / size, this offers a different way.
@terrestris/devs please review.
> Use center and zoom for zoomToExtent Button

- src/Button/ZoomToExtentButton/ZoomToExtentButton.tsx
Improve property checking for  `zoom`. A valid `zoom` of `0` must be accepted. Thanks @marcjansen @LukasLohoff 
@terrestris/devs please review!
> zoomToExtent improve property checking

- src/Button/ZoomToExtentButton/ZoomToExtentButton.tsx
- zoomToExtentButton: Fix import of `olCoordinate`
Background: First noticed, by using react-geo within react-geo-baseclient.
@terrestris/devs please check.
> Fix import statement zoomToExtentButton

- .github/workflows/on-publish.yml
This should fix the target path in the `gh-pages` branch (`docs/latest` instead of `docs/latest/styleguide`) and the version number.
Please note @terrestris/devs.
> Fix deploy path and version variable

- src/Panel/Panel/Panel.tsx
This fixes conflicts between drag and click events in mobile mode.  
Controls within a `Panel` titlebar weren't working when dragging is enabled in mobile mode.
Thanks to @LukasLohoff for the right hint.
Please note @terrestris/devs
> Fix conflicting events in Panel titlebar

- src/Field/NominatimSearch/NominatimSearch.tsx
This omits the `onSelect` type from the base component as the type differs from the one defined in our component.
> Omit onSelect as the typing differs from the base component

- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.spec.tsx
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.tsx
Fixes a bug that was introduced by https://github.com/terrestris/react-geo/pull/1959 and found with the react testing library tests.
> Fix CRS Combo

- src/Button/ToggleButton/ToggleButton.spec.tsx
- src/Button/ToggleButton/ToggleButton.tsx
Rewrites ToggleButton tests to react-testing-library.
Persists `lastClickEvent`
> Rewrite ToggleButton test

- src/LayerTree/LayerTree.tsx
Both props are defined in the `TreeProps` and can safely be removed from our own definition.
> Remove props draggable and checkable

- src/Button/ToggleGroup/ToggleGroup.tsx
Update state value for `selectedName` key if it's prop value was changed as well.
> Fix selectedName state value of ToggleButton

- src/Button/MeasureButton/MeasureButton.tsx
Deactivates drawInteraction and removes all measurements from the map if some measure button component will unmount.
> Ensure that measure button is properly deactivated on unmount

- .dependabot/config.yml
This adds a prefix to the dependabot commit messages so they conform the [angular commit message convention](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format).
> ci: Add prefix to dependabot commit messages

- src/Button/DigitizeButton/DigitizeButton.example.md
- src/Button/DigitizeButton/DigitizeButton.tsx
Version [15.1.0](https://github.com/terrestris/react-geo/releases/tag/v15.1.0) introduced the `DrawButton`, but keeps the `DigitizeButton` for backwards-compatibility and some unique options in it. This PR adds a short note about a potential deprecation of the `DigitizeButton`.
Please note @terrestris/devs.
> Add deprecation note in DigitizeButton

- package.json
Fix ordering of `@semantic-release` plugins loading according to the [official example](https://github.com/semantic-release/git#examples)
> Fix semantic release plugin order

- package-lock.json
- src/Button/CopyButton/CopyButton.example.md
- src/Button/CopyButton/CopyButton.spec.tsx
- src/Button/CopyButton/CopyButton.tsx
- src/Button/SelectFeaturesButton/SelectFeaturesButton.example.md
- src/Button/SelectFeaturesButton/SelectFeaturesButton.spec.tsx
- src/Button/SelectFeaturesButton/SelectFeaturesButton.tsx
- src/Util/rtlTestUtils.tsx
This PR adds a dedicated CopyButton that copies features on click. Also this PR addresses an issue with the SelectFeaturesButton which was clearing the feature collection on rerender. This is originally caused by the ToggleButton which seems to call `onToggle` on rerender. This change makes the button more robust regardless.
> Copy button

- src/Button/MeasureButton/MeasureButton.tsx
With this adjustment, duplicate labs are no longer drawn on the polygons during measurements
> fix: prevents double labels on measure polygon features

- .npmrc
This enables `engine-strict` to force `npm i` to work with `npm >= 7`. This will prevent rewriting the lockfile from version 1 to 2 and back.
> chore: enable engine-strict

- .github/workflows/on-publish.yml
This tries to fix the automated update of the gh-pages branch by running it on release creation. Not sure, by I assume the 
`published` one isn't triggered by the semantic-release process. In addition [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) allows for a manual trigger of the pipeline.
Potentially resolves #2313.
> Fix automated action run and allow manual execution

- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.tsx
- src/Provider/MapProvider/MapProvider.tsx
Fixes the following:
* in `CoordinateReferenceSystemCombo.tsx`: Strings must use singlequote
* in `MapProvider.tsx`: Missing semicolon
Compare e.g.:
Please review.
> Fix some GitHub check annotations

- package-lock.json
- package.json
- src/Button/CopyButton/CopyButton.tsx
- src/Button/DigitizeButton/DigitizeButton.tsx
- src/Button/DrawButton/DrawButton.tsx
- src/Button/GeoLocationButton/GeoLocationButton.tsx
- src/Button/MeasureButton/MeasureButton.tsx
- src/Button/ToggleGroup/ToggleGroup.tsx
- src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.tsx
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.tsx
- src/Field/NominatimSearch/NominatimSearch.tsx
- src/Field/ScaleCombo/ScaleCombo.tsx
- src/Field/WfsSearchInput/WfsSearchInput.tsx
- src/Grid/AgFeatureGrid/AgFeatureGrid.tsx
- src/HigherOrderComponent/TimeLayerAware/TimeLayerAware.tsx
- src/LayerSwitcher/LayerSwitcher.tsx
- src/LayerTree/LayerTree.spec.tsx
- src/LayerTree/LayerTree.tsx
- src/Legend/Legend.tsx
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.tsx
- src/Slider/LayerTransparencySlider/LayerTransparencySlider.tsx
- src/Slider/TimeSlider/TimeSlider.spec.tsx
- src/Slider/TimeSlider/TimeSlider.tsx
- src/Util/DigitizeUtil.ts
- src/Util/typeUtils.ts
- tsconfig.json
This enables the `noImplicitAny` option of typescript. Updates `ol-util` to version 6.0.0.
> fix: enable `noImplicitAny`

- src/LayerSwitcher/LayerSwitcher.spec.tsx
- src/LayerSwitcher/LayerSwitcher.tsx
* Fix index determination for currently visible layer
* Add warn message if all passed layers are invisible
> Fix layer switcher behaviour

- src/LayerSwitcher/LayerSwitcher.spec.tsx
- src/LayerSwitcher/LayerSwitcher.tsx
Adjust tests for LayerSwitcher component due to change introduced [here](https://github.com/terrestris/react-geo/pull/2431/files#diff-6f9e945c24cc487fc98341714164f118d6efabb32b2dde4d760f4c93bbdd1588L58)
> Fix layer switcher tests

- src/Button/MeasureButton/MeasureButton.tsx
Fixes the `geodesic` property of the MeasureButton.
> Geodesic optional

- src/Button/MeasureButton/MeasureButton.tsx
> fix(MeasureButton): make property `geodesic` a boolean with default value `true`

- src/Button/DigitizeButton/DigitizeButton.tsx
Do not propagate event in DigitizeButton to the translate interaction if already modifying.
> fix(DigitizeButton): do not propagate event to translate if modifying

- src/Button/DigitizeButton/DigitizeButton.tsx
- src/Button/ModifyButton/ModifyButton.tsx
Do not propagate event in DigitizeButton and ModifyButton to the translate interaction if already modifying.
> Do not propagate event to translate if modifying

- src/LayerSwitcher/LayerSwitcher.tsx
Reset reference to the map instance of original layer to ensure that the cloned layer will be properly assigned to the internal layer swticher map instance.
> Fix layer cloning for LayerSwitcher component

- src/Grid/PropertyGrid/PropertyGrid.spec.tsx
- src/Grid/PropertyGrid/PropertyGrid.tsx
The `PropertyGrid` component doesn't rerender on updated props (espacially while receiving a new feature) properly. 
This suggests to recalculate the `dataSource` and `columnDefs` accordingly and not on initial render only.
--
> Fix rerendering of the `PropertyGrid` on changed props

- jest.config.js
- package-lock.json
- package.json
- src/Button/PrintButton/InkmapTypes.ts
- src/Button/PrintButton/PrintButton.example.md
- src/Button/PrintButton/PrintButton.spec.tsx
- src/Button/PrintButton/PrintButton.tsx
- src/Field/WfsSearch/WfsSearch.tsx
- src/Field/WfsSearchInput/WfsSearchInput.tsx
- src/LayerTree/LayerTree.tsx
- src/custom.d.ts
- webpack.common.config.js
Introduces a client-side print component using [@camptocamp/inkmap](https://github.com/camptocamp/inkmap) which prints the map provided by the MapContext.
Currently supports:
- WMS layers
- WMTS layers
- GeoJSON vector layers
- OSM layers
Todos / open issues:
- support wfs layers
- support styles on feature level (if possible)
- fix issues with geostyler-openlayers-parser:
- if both fill and stroke are defined, stroke will be silently removed
- support for named colors
- add legend support (on the way)
- pass configuration options for scale bar, north arrow etc. to inkmap
> introduce client-side print component

- package-lock.json
- package.json
Actually the installation of `react-geo` in a project (without `husky`) fails with:
```
npm ERR! command sh -c husky install
npm ERR! sh: 1: husky: not found
```
This suggests to move the script from the `postinstall` to the `prepare` phase. Unlike `postinstall`, the `prepare` command does not run when a NPM package is installed as a dependency in another project.
> Move husky installation from postinstall to prepare phase

- src/Panel/SearchResultsPanel/SearchResultsPanel.less
- src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
- src/Util/ClickAwayListener/ClickAwayListener.tsx
- src/index.ts
Adds a search result panel that displays grouped search results. Also adds a click away handler component to detect clicks outside a given node.
Related to #881
> feat: add grouped search results panel

- src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
Fixes a lodash import.
Bug was introduced in #2652 
> fix: fix lodash import

- src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
This extends the props type of `<SearchResultsPanel>` to pass through antd properties. Through this, it is possible to configure antd `<Collapse>` and e.g. set all panels to be expanded by default.
> feat: add antd passThroughProps to SearchResultsPanel

- package.json
Newer npm version complain if there is a peerDependency mismatch. This way react-geo is more compatible.
> fix: use broader peer dependency

- src/Button/DrawButton/DrawButton.tsx
- src/Button/MeasureButton/MeasureButton.tsx
- src/Util/ClickAwayListener/ClickAwayListener.tsx
This prepares the update to ol >= 6.15 by fixing some outdated typings.
Unfortunately the update can't take place right now as our `inkmap` dependency isn't compatible with the newest ol version yet.
--
> Prepare ol update

- src/CoordinateInfo/CoordinateInfo.tsx
This introduces the prop `fetchOpts` for the `CoordinateInfo` component to set additional request options that will be applied to the GetFeatureInfo request. The options can be set for each `queryLayer` separately and will be identified by the internal layer id.
--
> Allow additional fetch opts for GFI per query layer

- src/Button/PrintButton/PrintButton.example.md
- src/Button/PrintButton/PrintButton.tsx
- manually add scalebar if value is `true` and reduce size
- fix legend spacing
> fix: minor scalebar print fixes

- .vscode/settings.json
Restore auto linting for *.(spec.).tsx classes for VS code editor.
> fix: properly reference lint config file for vs code editor

- src/Field/WfsSearchInput/WfsSearchInput.tsx
This adds a Bugfix as the default `maxFeatures` was `0` if not defined. New default is 1000.
It also adds the possibility to parse GML32 responses.
> Improvements to WFSSearchInput

- src/Field/WfsSearchInput/WfsSearchInput.tsx
This fixes the `WfsSearchInput` by adding missing `await` statements.
> Fixes WfsSearchInput

- src/LayerTree/LayerTree.tsx
Replaces the instanceof check with a function that is specific for layergroups.
> fix: replaces the instanceof check

- src/Panel/SearchResultsPanel/SearchResultsPanel.spec.tsx
- src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
This adds support for a custom list item prefix component in the `SearchResultsPanel`.
--
> Add support for a custom list item prefix in the `SearchResultsPanel`

- src/Field/WfsSearch/WfsSearch.example.md
> Configure maxFeatures in WFS search example

- src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.spec.tsx
- src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.tsx
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.example.md
- src/LayerTree/LayerTree.example.md
This PR makes the icons of `AddWmsLayerEntry`  more accessible by adding an `aria-label` to inline `<svg role="img>…</svg>`; this article suggests that this is a correct approach: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg
Additionally a bunch of eslint warnings in examples and tests are fixed.
The tests now make use of [`getByLabelText`](https://testing-library.com/docs/queries/bylabeltext/), I'd love to hear your opinions on this.
> Enhance the accessibility of icons in AddWmsLayerEntry

- src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
This PR adds new optional property `layerStyle` to the component `SearchResultPanel`.
Use this property to add a style to the highlighted feature on the highlighting layer. 
Example:
```jsx
<SearchResultsPanel
[…]
layerStyle={
new OlStyle({
stroke: new OlStroke({
color: 'rgb(255,0,0)',
width: 2
}),
fill: new OlFill({
color: 'rgba(255,255,255, 0.5)'
})
})
}
/>
```
@terrestris/devs please review.
> Adds layer style properties to search results panel

- src/LayerSwitcher/LayerSwitcher.spec.tsx
- src/LayerSwitcher/LayerSwitcher.tsx
This PR suggests to cahnge the LayerSwitcher, to conatin a `role="form"`, which is arguably the best choice (as far as I can tell, I'd love to hear what others think). Additionally, this changes how we test the component, and by that it removes annoying (but perhaps correct) `eslint` warnings.
None
> Better a11y, better test, less eslint warnings

- src/Util/typeUtils.spec.tsx
Originally I just wanted to increase coverage, and picked sth. supposedly trivial to test, but then I stumbled about the logic behind `isWmsLayer`:
- Is this needed in a typed world at all?
- if it is needed, is it likely used in many projects?
- does it make sense the way it is now, so that e.g. a vector layer with a wms source is considered a wms layer? The longer I look at the code the more wrong it looks to my eye.
-
> test: add some tests for isWmsLayer

- src/LayerTree/LayerTree.tsx
Layer visibility in the layer tree will also be toggled when clicking on the name instead on the checkbox.
> feat: toggle layer visibility when clicking on the name

- src/LayerTree/LayerTree.tsx
Disables the change from #3002 by default and makes in configurable via prop.
#3002 
> fix: make toggle on click configurable

- src/Map/MapComponent/MapComponent.tsx
Don't override the default children prop from `HTMLDivElement` as it accepts a broader range of acceptable child values.
--
> Remove unnecessary `children` prop in `MapComponent`

- src/LayerTree/LayerTree.tsx
- src/Legend/Legend.example.md
- src/Legend/Legend.spec.tsx
- src/Legend/Legend.tsx
This adds support for custom request headers (e.g. an authentication token) to the `<Legend>` component and also adds a loading indicator to it.
--
> Custom headers and a loading mask for the `Legend` component

- src/Field/NominatimSearch/NominatimSearch.example.md
- src/Field/NominatimSearch/NominatimSearch.spec.tsx
- src/Field/NominatimSearch/NominatimSearch.tsx
* Rewrite of `NominatimSearch` to be a Functional Component
* Adds a `debounceTime` prop (default: 300 ms) so that no requests are made while the user is still typing
* rewrites the test to use react-testing-library
* rewrites the example to use a map context and a FC
https://github.com/terrestris/react-geo/issues/2298
> feat(NominatimSearch): rewrite to FC, add debounceTime, use rtl for test

- src/LayerSwitcher/LayerSwitcher.spec.tsx
- src/LayerSwitcher/LayerSwitcher.tsx
- src/Map/MapComponent/MapComponent.tsx
This refactors the `LayerSwitcher` and the `MapComponent`. Both are transformed to react function components.
The `LayerSwitcher` is also restructured to have less internal functions and variables.
Two new optional properties where added ('identifierProperty', 'labelProperty') and the typing of the layers property is looser then before.
> Refactor `LayerSwitcher` and `MapComponent`

- src/Panel/SearchResultsPanel/SearchResultsPanel.less
- src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
Show optionally configured in header of search results collapse panels. If provided, the icon will be shown as avatar right to panel title and feature count.
Icon can be passed as string path or react node (e.g. FontAwesomeIcon).
> feat: add optional icon to header of SearchResultsPanel

- src/CoordinateInfo/CoordinateInfo.tsx
We're cloning the click coordinate and features to not pass the internal state reference to the parent component. Also note that we explicitly don't use `feature.clone()` to keep all feature properties (in particular the id) intact.
--
> fix: keep feature id in `CoordinateInfo`

- src/BackgroundLayerChooser/BackgroundLayerChooser.tsx
- src/BackgroundLayerPreview/BackgroundLayerPreview.tsx
Ensures that layers are always mapped.
> fix: enables layer array after no layer was selected

- src/CoordinateInfo/CoordinateInfo.tsx
Optimize fetch options in `CoordinateInfo` to handle either an object with request options per layer UID or a function returning options based on `WmsLayer`.
> Improve CoordinateInfo fetch options

- src/Button/MeasureButton/MeasureButton.tsx
Adds a measureRadius property, that when set to true, measures the radius of a circle instead of the area.
> feat: adds a radius property to the measure circle button

- src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
This PR adjusts the `SearchResultPanel` with an optional property (`extentShift`) to apply  an offset to the features extent of an entry in the search results. This can be used when the map is overlaid by elements and the map center is no longer the actual map center at that moment.
> Configurable onClick property for SearchResultPanel

- src/Button/SimpleButton/SimpleButton.spec.tsx
- src/Button/SimpleButton/SimpleButton.tsx
This refactors the `SimpleButton` to a function component.
> Refactor `SimpleButton` to function component

- src/Field/ScaleCombo/ScaleCombo.example.md
- src/Field/ScaleCombo/ScaleCombo.spec.tsx
- src/Field/ScaleCombo/ScaleCombo.tsx
This refactors the `ScaleCombo` to a function component.
Breaking change: props `map` and `zoomLevel` have been removed.
> Refactor `ScaleCombo` to function component

- package-lock.json
- package.json
- src/Field/NominatimSearch/NominatimSearch.example.md
- src/Field/NominatimSearch/NominatimSearch.tsx
Refactors the `NominatimSearch` component so that is uses new `useNominatim` hook proposed in https://github.com/terrestris/react-util/pull/600 
> feat: introduce useNominatim hook in NominatimSearch component

- jest.config.js
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.example.md
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.spec.tsx
- src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.tsx
Use `useProjFromEpsgIO` of https://github.com/terrestris/react-util/pull/595 and migrate `CoordinateReferenceSystemCombo` as function component.
> Refactor CoordinateReferenceSystemCombo to use useProjFromEpsgIO for CRS fetching

- package-lock.json
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.example.md
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.spec.tsx
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.tsx
- src/Slider/TimeSlider/TimeSlider.spec.tsx
- src/Slider/TimeSlider/TimeSlider.tsx
This refactors the `TimeLayerSiderPanel` and `TimeSlider` to a function component.
The property `map` of `TimeLayerSiderPanel` will be removed, as it was neither needed nor used.
> Refactor `TimeLayerSiderPanel` and `TimeSlider` to function component

- styleguide.config.js
This accelerates the startup of the styleguidist server in dev mode by the factor of ~5-10.
--
> Accelerate the start of the styleguide (in dev mode)

- src/Button/ToggleButton/ToggleButton.tsx
- src/CoordinateInfo/CoordinateInfo.tsx
This PR update the `ToggleButton` property `buttonTransparent` to `false` again and makes use of the `onSuccess` property in `CoordinateInfo` component.
:exclamation: After a new version of react-util is available, it must be referenced here in the package.json.
> Fix ToggleButton and make use of onSuccess in CoordinateInfo

- README.md
This PR suggests t use a different URL for the [Snyk badge](https://support.snyk.io/hc/en-us/articles/360003997277-Badge-Support-for-Repositories).
Before:
After:
(The background can be ignored)
> docs: use a supported URL for the Snyk badge

- src/Grid/PropertyGrid/PropertyGrid.example.md
- src/Grid/PropertyGrid/PropertyGrid.spec.tsx
- src/Grid/PropertyGrid/PropertyGrid.tsx
This adds a custom `render` function for the `PropertyGrid` value column.
If the value is a string an represents a link the value is renderer with an anchor element (`<a href="...">`).
> Render urls as anchor element

- package-lock.json
- package.json
- src/Field/NominatimSearch/NominatimSearch.tsx
- src/Field/WfsSearchField/WfsSearchField.tsx
Pass through on fetch success callbacks in WfsSearchField and NominatimSearchField.
Makes WfsSearchField more similar to NominatimSearchFielf by passing through args to `useWfs` and `Autocomplete`.
> feat: pass through on fetch success callbacks

- src/LayerTree/LayerTree.tsx
This simplifies the LayerTree by removing listeners in the useEffect cleanup functions.
> refactor: simplify LayerTree and more useCallback

- src/LayerSwitcher/LayerSwitcher.spec.tsx
- src/LayerSwitcher/LayerSwitcher.tsx
this changes the LayerSwitcher Component so it always shows the next layer instead of the current one.
> fix: layerswitcher always shows next layer instead of current layer

- src/Button/ToggleButton/ToggleButton.example.md
- src/Button/ToggleButton/ToggleButton.less
- src/Button/ToggleButton/ToggleButton.tsx
- src/index.ts
BREAKING CHANGE: This removes the buttonTransparent property. See the example on how to customize the color via the ConfigProvider.
By using the antd css variables we do not override the backgroundColor while still being able to style the button via the antd theming.
> fix: use antd css variables to make button active

- package-lock.json
- package.json
- src/CoordinateInfo/CoordinateInfo.example.md
BREAKING CHANGE: The input of the render function is no longer grouped by featureType
but returns an object for each feature that contains the feature, the layer and the feature type.
If you need the grouping, you can do the following
```
import { groupBy, mapValues } from 'lodash';
<CoordinateInfo
resultRenderer={({ features }) => {
const grouped = groupBy(features, 'featureType');
const groupedAndMapped = mapValues(grouped, results => results.map(r => r.feature));
// ...
}}
/>
```
See https://github.com/terrestris/react-util/pull/733
> feat: update coordinate button to use the new result value

- src/Legend/Legend.tsx
Adds a property that determines whether the loading mask shall be displayed or not.
> Configurable loading mask

- src/Button/MeasureButton/MeasureButton.less
- src/Button/ModifyButton/ModifyButton.tsx
add onFeatureSelect listener to modify button
> feat: add onFeatureSelect listener to modify button

- jest.config.cjs
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.example.md
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.less
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.tsx
This MR makes further adjustments to the `TimeLayerSliderPanel` and implements a spin to display the loading activity. The default of the autoplay function is set from seconds to hours.
> Further TimeLayerSliderPanel updates (loading spin)

- src/Button/SimpleButton/SimpleButton.tsx
Now the `type` prop is passed through to the `Button` component.
--
> Pass `type` prop to `Button`

- src/LayerTree/LayerTree.tsx
This allows to be notified whenever a layer is checked / unchecked, which was previously not possible. Overriding `onCheck` does not work for this, as it breaks the selection completely.
> Add optional layer visibility change callback

- src/FeatureLabelModal/FeatureLabelModal.tsx
Simply setting `autoFocus` will not work because antd renders the modal outside of the root element. See also https://github.com/ant-design/ant-design/issues/8668
> Enable drawbutton autofocus on text area

- src/LayerTree/LayerTree.tsx
This removes `onDragStart` from the layer tree title node.
Please note that if you want to use a draggable component inside the layer tree title node via `nodeTitleRenderer`, you will have to stop drag events on that node yourself. This can be done by applying the properties to the child node.
Example change:
https://github.com/terrestris/shogun-gis-client/pull/1777
Source PR: https://github.com/terrestris/react-geo/pull/3894
> Fix drag and drop in LayerTree

- README.md
- package-lock.json
- package.json
- src/Grid/AgFeatureGrid/AgFeatureGrid.tsx
This updates AG-Grid to v33. This changes the npm package names and introduces a new way to theme the grid via react properties. This is easier to customize and is similar to the new antd way.
This is a breaking change.
This is how the old version (left side) looks compared to the new version (right side):
This PR also adds some documentation about theming with antd.
> Ag grid update theming

- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.tsx
> fix: initial range determination in time layer slider panel

- .github/workflows/release.yaml
- .releaserc
- src/LayerSwitcher/LayerSwitcher.tsx
This PR fixes a bug in the zoom behavior of the main map for v24 when the `LayerSwitcher` is included. Previously a too small scale was reached when zooming in. The user expected to zoom closer to the selected area by dragging a box.  
This is achieved by synchronizing the view between the main map and the preview map, instead of using the same view:
Old behavior:  
New behavior:  
> Fixes a zoom error in LayerSwitcher

- src/Button/DrawCutButton/DrawCutButton.tsx
This exposes the `onCutEnd` callback in the `DrawCutButton` through the interface.
> fix: expose onCutEnd callback in DrawCutButton

- src/Grid/FeatureGrid/FeatureGrid.example.md
- src/Grid/FeatureGrid/FeatureGrid.spec.tsx
- src/Grid/FeatureGrid/FeatureGrid.tsx
In the current `FeatureGrid` implementation it's not possible to fully override the auto-generated column definition, e.g. to pass the order or additional columns that do not exist in the passed features. This PR suggests to (re-)add this possibility by passing the `columns` prop. The existing prop `columns` has been renamed to `columnDefs` (**BREAKING CHANGE**).
--
> Allow to override column definition in `FeatureGrid` again

- src/Button/CopyButton/CopyButton.tsx
- src/Button/DeleteButton/DeleteButton.tsx
All other buttons are calling their respective `on...End` events after the action is performed. The `DeleteButton` and the `CopyButton` were the only ones calling the event before it actually has been performed.
> fix: fire delete event after removal of feature from source

- src/BackgroundLayerChooser/BackgroundLayerChooser.tsx
- src/BackgroundLayerPreview/BackgroundLayerPreview.tsx
This adds a new optional property `titleRenderer` to the `BackgroundLayerChooser` to specify a custom title per layer.
--
> Allow to pass custom title renderer

- src/BackgroundLayerChooser/BackgroundLayerChooser.tsx
This (re-)adds support for WMTS layers/sources in the `BackgroundLayerChooser`.
--
> Readd support for wmts layers/sources in `BackgroundLayerChooser`

- package-lock.json
- package.json
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.example.md
- src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.tsx
- src/Slider/TimeSlider/TimeSlider.spec.tsx
- src/Slider/TimeSlider/TimeSlider.tsx
* Add support for ISO 8601 duration strings (e.g., "PT1H")  in `TimeSlider` / `TimeSliderPanel` to automatically generate appropriate step intervals.
* Add a new property `markFormatString` to allow user-defined formatting of the mark labels on the slider.
* When duration is passed, marks are determined automatically (`TimeSliderPanel`).  The maximum number of marks can be limited with `maxNumberOfMarks`
* Improvement: Both `formatString` and `duration` can now be passed either as component props or via the corresponding layer properties — ensuring consistent and flexible configuration.
Plz review @terrestris/devs 
> Feature(TimeSlider): create steps based on passed duration

- src/Field/SearchField/SearchField.less
- src/Field/SearchField/SearchField.tsx
Makes the `SearchField` usable in more generic contexts:
- new property `onSearchCompleted` is a callback that returns all the search results
- new property `autoCompleteDisabled` (default: false) allows to disable the autocomplete dropdown
- in this case, the property `getValue` is no longer required
With these new properties, the `SearchField` can be used with a custom result display, e.g.:
```tsx
[...]
const onSearchCompleted = async (result: FeatureCollection | undefined) => {
setData(result);
};
return (
<div>
<SearchField
zoomToFeature={false}
onSearchCompleted={onSearchCompleted}
searchFunction={wfsSearchFunction}
autoCompleteDisabled={true}
/>
{
(
<AgFeatureGrid
features={features}
loading={isLoading}
zoomToExtent={false}
/>
)
}
</div>
);
``` …
> allow SearchField with external data display

- package.json
This Pr suggests to correct the spelling of an npm command. I am not sure how this could live so long undetected herein.
none
> chore: fix misspelled command
