src/Util/UndoUtil.js, src/Util/UndoUtil.spec.js
This PR adds an UndoUtil helper class from a client project. It is ported with the minimum needed changes, and without additional tests.
Please review.
=> Add UndoUtil helper class

.travis.yml
Reverts terrestris/react-geo#26
=> Revert "WIP"

src/Button/SimpleButton/SimpleButton.less, src/Button/ToggleButton/ToggleButton.less
Append the styles to `button` elements only.
=> Adjust button styles 

src/index.js
=> Export all available utils

.travis.yml, package.json
… and add `npm install react` to travis.yml
=> Remove react as normal dependency

src/index.js
=> Add missing exports

package.json, src/Util/UrlUtil.js, src/Util/UrlUtil.spec.js, src/index.js
This adds an URL utility class.
=> Add url util

src/Button/SimpleButton/SimpleButton.spec.jsx, src/Button/ToggleButton/ToggleButton.spec.jsx, src/Button/ToggleGroup/ToggleGroup.spec.jsx, src/LayerTree/LayerTree.spec.jsx, src/Legend/Legend.spec.jsx, src/Map/FloatingMapLogo/FloatingMapLogo.spec.jsx, src/Map/ScaleCombo/ScaleCombo.spec.jsx, src/Panel/Panel/Panel.spec.jsx, src/Panel/Titlebar/Titlebar.spec.jsx, src/Toolbar/Toolbar.spec.jsx, src/UserChip/UserChip.spec.jsx, src/Util/CsrfUtil.spec.js, src/Util/FeatureUtil.spec.js, src/Util/MapUtil.spec.js, src/Util/ObjectUtil.spec.js, src/Util/StringUtil.spec.js, src/Util/UndoUtil.spec.js, src/Util/UrlUtil.spec.js, src/VisibleComponent/VisibleComponent.spec.jsx, src/index.js
=> Import classes from index.js to ensure they're exported

.babelrc, karma.conf.js, src/Button/SimpleButton/SimpleButton.spec.jsx, src/Button/ToggleButton/ToggleButton.spec.jsx, src/Button/ToggleGroup/ToggleGroup.spec.jsx, src/LayerTree/LayerTree.spec.jsx, src/Legend/Legend.spec.jsx, src/Map/FloatingMapLogo/FloatingMapLogo.spec.jsx, src/Map/ScaleCombo/ScaleCombo.spec.jsx, src/Panel/Panel/Panel.spec.jsx, src/Toolbar/Toolbar.spec.jsx, src/UserChip/UserChip.spec.jsx, src/Util/MapUtil.spec.js, src/Util/TestUtil.js, src/VisibleComponent/VisibleComponent.spec.jsx
Title says it all. See also #56.
Please review.
=> Rename TestUtils to TestUtil

src/Slider/LayerTransparencySlider.example.jsx, src/Slider/LayerTransparencySlider.example.md, src/Slider/LayerTransparencySlider.jsx, src/Slider/LayerTransparencySlider.spec.jsx, src/index.js, webpack.examples.config.js
This introduces the `LayerTransparencySlider`.
=> Add LayerTransparencySlider

package-lock.json, package.json
Updates `react-rnd` to the latest version (see #72).
=> Update react-rnd to the latest version

src/Panel/Titlebar/Titlebar.less
Center titlebar items vertically and move control tools to the right (without float).
=> Minor titlebar style adjustments

src/Button/SimpleButton/SimpleButton.jsx, src/Button/ToggleButton/ToggleButton.jsx
This refactors the `SimpleButton` and `ToggleButton` as there were some issues with the scope and props.
=> Refactor buttons

package-lock.json, package.json, src/Field/NominatimSearch/NominatimSearch.example.jsx, src/Field/NominatimSearch/NominatimSearch.example.md, src/Field/NominatimSearch/NominatimSearch.jsx, src/Field/NominatimSearch/NominatimSearch.spec.jsx, src/index.js, webpack.examples.config.js
This introduces the `NominatimSearch` component.
It also adds the `lint:fix` script to the package.json
=> Introduces NominatimSearch component

src/Panel/Panel/Panel.jsx, src/Panel/Panel/Panel.less, src/Panel/Panel/Panel.spec.jsx
This updates the style of `Panel`:
* Drop a shadow if a panel is used as window.
* Update the height if the panel is collapsed correctly.
=> Some styling for the Panel

package.json
~Please review.~ Edit Doesn't need a formal review, it is not touching any logic or styling
=> Make 'npm run lint:fix' definition less verbose

karma.conf.js
This adds these timeout config params to the karma.conf.js:
- captureTimeout
- browserDisconnectTolerance
- browserDisconnectTimeout
- browserNoActivityTimeout
=> Adds timeout-config to karma.conf.js

package-lock.json, src/Button/SimpleButton/SimpleButton.example.jsx, src/Button/ToggleButton/ToggleButton.example.jsx, src/Button/ToggleGroup/ToggleGroup.example.jsx, src/HigherOrderComponent/VisibleComponent/VisibleComponent.example.jsx, src/LayerTree/LayerTree.example.jsx, src/Legend/Legend.example.jsx, src/Map/FloatingMapLogo/FloatingMapLogo.example.jsx, src/Map/ScaleCombo/ScaleCombo.example.jsx, src/Panel/Panel/Panel.example.jsx, src/Panel/Titlebar/Titlebar.example.jsx, src/Slider/LayerTransparencySlider.example.jsx, src/Toolbar/Toolbar.example.jsx, src/UserChip/UserChip.example.jsx
=> Update imports in examples to look at index.js

src/Button/ToggleButton/ToggleButton.jsx, src/Panel/Titlebar/Titlebar.jsx, src/Panel/Titlebar/Titlebar.spec.jsx, src/Toolbar/Toolbar.less, src/UserChip/UserChip.jsx
* Make use of correct class identifier in the `UserChip`.
* Remove fix positioning in `VerticalToolbar`.
* Don't render the tools span if no tool is provided in `Titlebar`.
=> Unsorted minor fixes

src/Legend/Legend.jsx
=> This adds the passThorughProps to the Legend

src/Button/SimpleButton/SimpleButton.jsx, src/Util/UndoUtil/UndoUtil.js
- Fixes icon bug in SimpleButton.jsx
- Fixes undefined bug in UndoUtil.js
=> Minor Bugfixes

README.md
=> Add snyk vulnerabilities badge to README

package-lock.json, package.json
=> Greenkeeper/react i18next 6.0.6

package-lock.json, package.json
=> Greenkeeper/url loader 0.6.2

package-lock.json, src/LayerTree/LayerTree.jsx, src/LayerTree/LayerTree.spec.jsx
This reverses the previouse order of TreeNodes.
Layer that are on top of the map are now on top in the tree.
@terrestris/devs plz review
=> Reverse order of TreeNodes

package.json
=> Our name shall be '@terrestris/react-geo'

src/LayerTree/LayerTree.example.jsx, src/LayerTree/LayerTree.jsx, src/LayerTree/LayerTree.spec.jsx
This introduces a filterFunction for the LayerTree.
This adds the possibility to exclude layers from the LayerTree by a given filterFunction.
=> LayerTree filterFunction

src/HigherOrderComponent/MapProvider/MapProvider.jsx
=> Fixes a bug when using map in MapProvider

src/Grid/FeatureGrid/FeatureGrid.example.jsx, src/Grid/FeatureGrid/FeatureGrid.example.md, src/Grid/FeatureGrid/FeatureGrid.jsx, src/Grid/FeatureGrid/FeatureGrid.less, src/Grid/FeatureGrid/FeatureGrid.spec.jsx, src/index.js, webpack.examples.config.js
This PR adds a simple feature grid showing the attributes / values of a single features in a table.
=> Introduce feature grid

src/LayerTree/LayerTree.example.jsx, src/LayerTree/LayerTree.jsx, src/LayerTree/LayerTree.spec.jsx
Titkle says it all. Please review.
=> LayerTree: Take the layerGroup from the map if not provided

src/CircleMenu/CircleMenu.example.jsx, src/CircleMenu/CircleMenu.example.md, src/CircleMenu/CircleMenu.jsx, src/CircleMenu/CircleMenu.less, src/CircleMenu/CircleMenu.spec.jsx, src/CircleMenu/CircleMenuItem/CircleMenuItem.jsx, src/CircleMenu/CircleMenuItem/CircleMenuItem.less, src/CircleMenu/CircleMenuItem/CircleMenuItem.spec.jsx, src/index.js, src/style/variables.less, webpack.examples.config.js
It's finally here. The circle-menu.
It arranges React-Nodes in an circle with a specified diameter. You will mostly use it for Buttons.
=> CircleMenu

package-lock.json, package.json
=> Greenkeeper/i18next 10.2.1

src/Button/MeasureButton/MeasureButton.example.jsx, src/Button/MeasureButton/MeasureButton.jsx, src/Button/MeasureButton/MeasureButton.spec.jsx, src/Button/SimpleButton/SimpleButton.jsx, src/Button/SimpleButton/SimpleButton.spec.jsx, src/Button/ToggleButton/ToggleButton.example.jsx, src/Button/ToggleButton/ToggleButton.jsx, src/Button/ToggleButton/ToggleButton.spec.jsx, src/Button/ToggleGroup/ToggleGroup.example.jsx, src/Button/ToggleGroup/ToggleGroup.jsx, src/Button/ToggleGroup/ToggleGroup.spec.jsx
- Pass evt to Callbacks
- Mark onClick / onToggle with .isRequired
- Enhance docs
=> Refactors the Buttons

src/LayerTreeNode/LayerTreeNode.jsx, src/LayerTreeNode/LayerTreeNode.spec.jsx
=> Fix PropType in LayerTreeNode and adds some tests

dist/Button/SimpleButton/SimpleButton.js, dist/Button/ToggleButton/ToggleButton.js, dist/Util/MapUtil/MapUtil.js, src/Button/SimpleButton/SimpleButton.jsx, src/Button/ToggleButton/ToggleButton.jsx, src/Util/MapUtil/MapUtil.js, src/Util/MapUtil/MapUtil.spec.js
- Change MapUtil getLayer method
- Fixes No.1 in #266  (mutliple measurelayers)
- Removes Loggerstuff from simple and togglebutton
=>  Change MapUtil getLayer method & fix buttons

package-lock.json, package.json, src/Button/MeasureButton/MeasureButton.spec.jsx, src/Button/SimpleButton/SimpleButton.spec.jsx, src/Button/ToggleButton/ToggleButton.spec.jsx, src/Button/ToggleGroup/ToggleGroup.spec.jsx, src/Container/AddWmsPanel/AddWmsPanel.spec.jsx, src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.spec.jsx, src/Field/NominatimSearch/NominatimSearch.spec.jsx, src/Field/ScaleCombo/ScaleCombo.spec.jsx, src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.spec.jsx, src/LayerTree/LayerTree.spec.jsx, src/Util/CsrfUtil/CsrfUtil.spec.js, src/Util/MapUtil/MapUtil.spec.js, src/Util/ProjectionUtil/ProjectionUtil.spec.js
=> Use jest.spyOn and jest.fn instead of sinon.spy

package.json, src/Button/MeasureButton/MeasureButton.spec.jsx, src/Button/ToggleButton/ToggleButton.example.jsx, src/Button/ToggleButton/ToggleButton.jsx
=> Enable eslint for jsx

src/Window/Window.less
* Hide overflowed text in window title
Plz review.
=> Enhance title text style of Window component

package-lock.json, package.json
=> Greenkeeper/jest 22.0.3

package.json, src/Util/UrlUtil/UrlUtil.js, src/Util/UrlUtil/UrlUtil.spec.js
This adds the following methods to the `URLUtil`:
* getQueryParam()
* hasQueryParam()
* createValidGetCapabilitiesRequest()
* isValid()
=> Add some methods to the URLUtil

dist/Button/ToggleButton/ToggleButton.js, dist/Button/ToggleGroup/ToggleGroup.js, package-lock.json, src/Button/ToggleButton/ToggleButton.jsx, src/Button/ToggleGroup/ToggleGroup.jsx, src/Button/ToggleGroup/ToggleGroup.spec.jsx
As title says, this PR implements a `componentWillReceiveProps` for `ToggleGroup` component to be able to set possibly changed `selectedName` property.
=> Added componentWillReceiveProps method for ToggleGroup component

package-lock.json, package.json
=> Update to eslint 4.15.0

src/HigherOrderComponent/MapProvider/MapProvider.spec.jsx
Hat-tip to @dnlkoch, :kissing_heart:
=> Add tests for MapProvider

package-lock.json, package.json
=> Greenkeeper/babel eslint 8.2.1

package-lock.json, src/Button/MeasureButton/MeasureButton.example.jsx, src/CircleMenu/CircleMenu.example.jsx, src/Container/AddWmsPanel/AddWmsPanel.example.jsx, src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.example.jsx, src/Field/NominatimSearch/NominatimSearch.example.jsx, src/Field/ScaleCombo/ScaleCombo.example.jsx, src/Legend/Legend.example.jsx, src/Map/MapComponent/MapComponent.example.jsx, src/Slider/LayerTransparencySlider.example.jsx, tasks/build-examples.js
=> Change examples to be clearer and working on mobile

.ci/update-gh-pages.sh
See also this https://www.codacy.com/app/marcjansen/react-geo/issues/index?&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlIFN0eWxlIl19XQ== suggestion.
=> Use $() insteadof backtick operator

src/Map/MapComponent/MapComponent.jsx
=> Update the map size after update of component

package-lock.json, package.json
=> Greenkeeper/image webpack loader 4.0.0

.github/pull_request_template.md
This introduces a pull request template.
=> Introduces pull request template

package-lock.json, package.json
=> Greenkeeper/antd 3.1.6

package-lock.json, package.json
=> Greenkeeper/react i18next 7.3.4

package-lock.json
=> Updates package-lock.json

src/Util/StringUtil/StringUtil.js
I think this is way safer do do it this way, [SO agrees](https://stackoverflow.com/a/47140708). Please review.
=> Use DOMParser to strip out HTML

src/Button/DigitizeButton/DigitizeButton.jsx, src/Button/DigitizeButton/DigitizeButton.spec.jsx
* Set `ol.style.Style` object on drawn feature (previously the style was set on source of `digitizeLayer`)
* Added `styleFunction` for selected feature which will be applied if `ol.interaction.Select` in `editType=Edit` mode is activated.
=> Set style on drawn features

src/Button/ToggleButton/ToggleButton.jsx
This fixes the `componentWillReceiveProps` of the `ToggleButton`.
As the style is affected by the buttons `state` not its `props` we have to check against the state in cwr, too.
=> Fix componentWillReceiveProps of togglebutton

.babelrc, package-lock.json, package.json
This replaces the babel-preset-2015 package with babel-preset-env as recommended by babel: http://babeljs.io/env
=> Replace babel-preset-2015 with babel-preset-env

package-lock.json, package.json
Updates babel plugin import to version 1.6.5
Closes #404
=> Greenkeeper/babel plugin import 1.6.5

package-lock.json, package.json, src/Button/UploadButton/UploadButton.example.jsx, src/Button/UploadButton/UploadButton.example.md, src/Button/UploadButton/UploadButton.jsx, src/Button/UploadButton/UploadButton.less, src/Button/UploadButton/UploadButton.spec.jsx, src/index.js, webpack.examples.common.config.js
This introduces the `UploadButton`. In advantage to the ant design Upload you can pass in any child.
This also adds `webpack-cli` as it is required to build the examples.
=> Introduces the UploadButton

example-templates/basic.hbs, package.json, tasks/build-examples.js, webpack.common.config.js, webpack.examples.common.config.js, webpack.examples.development.config.js, webpack.examples.production.config.js
This updates `webpack` (and `webpack-dev-server`) to version 4 and adapts the configuration to match the changed configuration API.
Due to the update the (warm) build duration for the examples decreased from *24961ms* to *11315ms* on my local dev machine whereas the actual build sizes are nearly unchanged (with a minor tendency to smaller builds).
Closes #438 and #440.
=> Update to webpack 4

package-lock.json, package.json
This updates `jest` to `v22.4.2`
=> Upgrade jest to v22.4.2

package-lock.json, package.json
This updates `webpack-cli` to version `2.0.10`. Follow up of #446 because of package-lock merge conflicts.
=> Update webpack-cli to the latest version

package-lock.json, package.json
=> Greenkeeper/url loader 1.0.1

README.md, package.json, webpack.examples.common.config.js
Know that we have `less-loader` in version 4.1.0 `less` should be updateable to version 3.0.1.
closes #406
=> Update less to 3.0.1

src/Field/ScaleCombo/ScaleCombo.jsx
This fixes the input filter for the `ScaleCombo` component.
Fixes #224
=> Sets filteroption  in ScaleCombo

src/Util/GeometryUtil/GeometryUtil.example.jsx, src/Util/GeometryUtil/GeometryUtil.example.md, webpack.examples.common.config.js
This adds some examples for the `GeometryUtil`.
:exclamation: Requires #472 to be merged previously.
=> GeometryUtil examples

package-lock.json, package.json
=> Greenkeeper/query string 6.0.0

src/Button/DigitizeButton/DigitizeButton.jsx, src/Button/DigitizeButton/DigitizeButton.spec.jsx
This fixes buggy behaviour of the `DigitizeButton`.
- Most important fix is to not set a style on the feature but use the existing style functions.
- The label is know set as an feature attribute not at the style.
=> Fixes DigitizeButton bugs

assets/gh-index.html
this fixes the wrong link to the example page
=> fixed link to example page

package.json
:exclamation: This downgrades query-string to version 5.1.1 due to issues with version 6.0.0 and webpack 3.
=> Revert query-string update

src/LayerTree/LayerTree.jsx, src/Panel/Panel/Panel.jsx, src/Panel/Titlebar/Titlebar.less, src/Slider/TimeSlider.jsx, src/Slider/TimeSlider.spec.jsx, src/Util/AnimateUtil/AnimateUtil.js, src/Util/CsrfUtil/CsrfUtil.js, src/Util/MapUtil/MapUtil.js, src/Util/MeasureUtil/MeasureUtil.js, src/Util/UrlUtil/UrlUtil.js
=> Various updates to class methods

src/Field/ScaleCombo/ScaleCombo.jsx
=> Fix docs of scale combo

src/Button/ZoomInButton/ZoomInButton.example.jsx, src/Button/ZoomInButton/ZoomInButton.example.md, src/Button/ZoomInButton/ZoomInButton.jsx, src/Button/ZoomInButton/ZoomInButton.spec.jsx, src/index.js, webpack.examples.common.config.js
=> Add a zoom in button

src/Slider/MultiLayerSlider/MultiLayerSlider.example.jsx, src/Slider/MultiLayerSlider/MultiLayerSlider.example.md, src/Slider/MultiLayerSlider/MultiLayerSlider.jsx, src/Slider/MultiLayerSlider/MultiLayerSlider.spec.jsx, src/index.js, webpack.examples.common.config.js
This adds a MultiLayerSlider component
see test, example and description for details
=> Adding MultiLayerSlider component

.eslintrc, src/Button/SimpleButton/SimpleButton.jsx, src/CircleMenu/CircleMenu.jsx, src/LayerTree/LayerTree.spec.jsx, src/Map/FloatingMapLogo/FloatingMapLogo.spec.jsx, src/Panel/Panel/Panel.jsx, src/UserChip/UserChip.spec.jsx, src/Util/CsrfUtil/CsrfUtil.js, src/Util/MeasureUtil/MeasureUtil.spec.js
=> Enable and obey 'space-infix-ops' eslint rule

.npmrc, .travis.yml
This disables the generation of the `package-lock.json`. See #455.
Fixes #455
=> Disable generation of package-lock.json

src/Util/MapUtil/MapUtil.js, src/Util/MapUtil/MapUtil.spec.js
This PR adds a further util returning the list of layers matching the given pair of properties.
=> MapUtil - Add util filtering layers by property

src/HigherOrderComponent/DropTargetMap/DropTargetMap.example.md
Fixes linting error I recently introduced.
=> Fix linting error

src/Toolbar/Toolbar.less
This updates the styles of the `Toolbar`.
The change is small but the impact might be bigger. Any application side fix of the old 'broken' style might cause some ugly behaviour in current applications.
Examples should look the same as they do now.
Not sure how it would be correctly versioned with semver. API will not be broken but it's not a 'safe' update as your application might look different.
=> Updates/Synchronizes Toolbar styles

src/Util/GeometryUtil/GeometryUtil.js, src/Util/GeometryUtil/GeometryUtil.spec.js
=> GeometryUtil - Allow union operation for Multipolygons

src/Panel/Panel/Panel.jsx, src/Panel/Panel/Panel.less, src/Panel/Panel/Panel.spec.jsx, src/Window/Window.example.md
introduced `onKeyDown` property and event listener to handle pressing of `escape` keyboard key for window or panel component.
Listener will only be activated if the parent panel or window component provides `onEscape` property.
This feature can be useful to close windows or panels by pressing `escape` key instead of clicking close button.
=> introduced onKeyDown event listener to handle escape key

src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.spec.jsx, src/Field/NominatimSearch/NominatimSearch.spec.jsx
Some tests were failing due to some incorrectly configurated mock objects used inside.
please review @KaiVolland
=> Fixed tests for CoordinateReferenceSystemCombo and NominatimSearch components

src/Button/DigitizeButton/DigitizeButton.jsx, src/Button/GeoLocationButton/GeoLocationButton.jsx, src/Button/MeasureButton/MeasureButton.jsx, src/Button/SimpleButton/SimpleButton.jsx, src/Button/ToggleButton/ToggleButton.jsx, src/Button/ToggleGroup/ToggleGroup.jsx, src/Button/UploadButton/UploadButton.jsx, src/Button/ZoomButton/ZoomButton.jsx, src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx, src/CircleMenu/CircleMenu.jsx, src/CircleMenu/CircleMenuItem/CircleMenuItem.jsx, src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.jsx, src/Field/NominatimSearch/NominatimSearch.jsx, src/Field/ScaleCombo/ScaleCombo.jsx, src/Field/WfsSearch/WfsSearch.jsx, src/Grid/PropertyGrid/PropertyGrid.jsx, src/LayerTree/LayerTree.jsx, src/LayerTreeNode/LayerTreeNode.jsx, src/Legend/Legend.jsx, src/Map/FloatingMapLogo/FloatingMapLogo.jsx, src/Panel/Panel/Panel.jsx, src/Panel/Titlebar/Titlebar.jsx, src/Slider/MultiLayerSlider/MultiLayerSlider.jsx, src/Toolbar/Toolbar.jsx, src/UserChip/UserChip.jsx, src/Window/Window.jsx, src/constants.js
This adds and uses a new constant `CSS_PREFIX`.
Please review.
=> Add and use a CSS_PREFIX constant

.github/pull_request_template.md
This updates the PR template to also include the category DOCUMENTATION
=> Add category DOCUMENTATION to PR template

src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.jsx, src/Field/NominatimSearch/NominatimSearch.jsx, src/Field/ScaleCombo/ScaleCombo.jsx, src/Field/WfsSearch/WfsSearch.jsx, src/Grid/FeatureGrid/FeatureGrid.jsx, src/Grid/PropertyGrid/PropertyGrid.jsx, src/LayerTree/LayerTree.jsx, src/Legend/Legend.jsx, src/Map/FloatingMapLogo/FloatingMapLogo.jsx, src/Panel/Panel/Panel.jsx, src/Panel/Titlebar/Titlebar.jsx, src/Slider/MultiLayerSlider/MultiLayerSlider.jsx, src/Slider/TimeSlider.jsx, src/Toolbar/Toolbar.jsx, src/UserChip/UserChip.jsx, src/Window/Window.jsx
This PR harmonizes the documentation of the className prop.
=> Harmonize documentation of className prop

src/Button/ZoomToExtentButton/ZoomToExtentButton.jsx
Title says it all, just a change of the default props.
=> Zoom faster to an extent

src/Button/UploadButton/UploadButton.jsx, src/Button/ZoomButton/ZoomButton.jsx, src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.jsx, src/Field/ScaleCombo/ScaleCombo.jsx, src/Map/FloatingMapLogo/FloatingMapLogo.jsx, src/Map/MapComponent/MapComponent.jsx, src/Panel/Titlebar/Titlebar.jsx, src/Toolbar/Toolbar.jsx, src/UserChip/UserChip.jsx
This replaces `representating` with `representing` in our codebase.
Please review,
=> Change wording: s/representating/representing/g

src/Button/GeoLocationButton/GeoLocationButton.jsx, src/Field/WfsSearch/WfsSearch.jsx, src/Panel/Panel/Panel.jsx
This replaces `PropType.object` with a more dedicated `PropType.shape` at two places.
Please review.
=> Make use of PropTypes.shape

src/Button/DigitizeButton/DigitizeButton.jsx
This adds a check for the `DigitizeButton` to make sure new interactions are added to the map 
=> Added a check for digitizerLayer's existance on the map

src/Slider/MultiLayerSlider/MultiLayerSlider.jsx
Resolves an annoying warning in the debugger console.
=> Add missing instanceOf() check

src/Util/FileUtil/FileUtil.jsx, src/Util/FileUtil/FileUtil.spec.jsx
This adds tests for the `FileUtil`.
The shapeimport function is still untested and should be tested in the future.
=> Introduces tests to FileUtil

src/HigherOrderComponent/DropTargetMap/DropTargetMap.jsx, src/HigherOrderComponent/DropTargetMap/DropTargetMap.spec.jsx
This adds some tests to the `DropTargetMap` HOC.
It also does some minor refactoring to the component itself.
=> Adds tests for DropTargetMap HOC + minor refactoring

package.json
=> chore(package): update react-styleguidist to version 7.0.13

src/CircleMenu/CircleMenu.spec.jsx, src/CircleMenu/CircleMenuItem/CircleMenuItem.spec.jsx
This tries to fix the randomly failing tests in the Node 10 environment by returning Promises in the asynchronous `CircleMenu` / `CircleMenuItem` tests.
=> Return Promises in async CircleMenu / CircleMenuItem tests

package.json
=> chore(package): update react-styleguidist to version 7.0.16

package.json
=> chore(package): update antd to version 3.6.1

package.json, src/Button/ToggleButton/ToggleButton.jsx, src/Button/ToggleButton/ToggleButton.spec.jsx, src/Button/ToggleGroup/ToggleGroup.jsx, src/Button/ToggleGroup/ToggleGroup.spec.jsx
This PR attempts to refactor the `ToggleButton` and adds some test for it thanks to @dnlkoch. The `ToggleGroup` button is also fixed for now. But we must decide if we want to keep it at all or not.
Plz review.
=> Togglebutton refactor

src/Button/DigitizeButton/DigitizeButton.jsx
This adds some (optional) props to the `DigitizeButton` to pass custom interaction config options as well as listener methods.
=> Add props to DigitizeButton

package.json
=> fix(package): update ag-grid to version 18.0.1

src/Slider/TimeSlider.jsx
This removes an unneeded wrapping div from the `TimeSlider`.
=> Removes unneeded div from TimeSlider

package.json
=> chore(package): update eslint-plugin-html to version 4.0.5

package.json
=> chore(package): update react-styleguidist to version 7.0.20

package.json
=> chore(package): update webpack to version 4.13.0

package.json
=> fix(package): update react-rnd to version 8.0.2

package.json
=> chore(package): update less to version 3.7.0

src/Button/GeoLocationButton/GeoLocationButton.jsx
This adds a `name` property to the layer created by the `GeoLocationButton`.
=> Adds name to geolocation layer

package.json
=> chore(package): update react-styleguidist to version 7.1.3

src/Panel/Panel/Panel.jsx
This filters the props to be passed to the `Rnd` component correctly.
Credits to @annarieger!
=> Fix panel pass through props

jest.config.js, package.json
=> Update antd dependency

package.json
=> Greenkeeper/monorepo.enzyme 3.4.4

package.json
=> Greenkeeper/monorepo.enzyme 3.5.0

package.json
=> chore(package): update react-styleguidist to version 7.3.4

package.json
=> Greenkeeper/monorepo.enzyme 1.4.0

package.json
Update `@terrestris/ol-util` to version 0.2.0.
=> Upgrades ol-util to 0.2.0

src/Container/AddWmsPanel/AddWmsPanel.example.md, src/Field/WfsSearch/WfsSearch.jsx, src/Grid/FeatureGrid/FeatureGrid.example.md, src/Grid/PropertyGrid/PropertyGrid.jsx, src/Panel/Panel/Panel.example.md
This fixes several issues with the documentation:
- Broken dependencies
- Broken links
- Typos
Fixes #861
=> Fixes several issues with the documentation

src/Grid/AgFeatureGrid/AgFeatureGrid.jsx
This adds an optional `onMapSingleClick` to the `AgFeatureGrid`.
=> Add onMapSingleClick callback

src/Button/UploadButton/UploadButton.jsx, src/Button/ZoomButton/ZoomButton.jsx
* Minor wording change in ZoomButton docs
* Clarify that drag and drop is supported
=> Several documentation updates

package.json
=> chore(package): update babel-plugin-import to version 1.9.1

package.json
=> Greenkeeper/monorepo.enzyme 3.7.0

package.json
=> fix(package): update @terrestris/ol-util to version 1.5.0

package.json
=> chore(package): update react-styleguidist to version 7.3.10

package.json
=> chore(package): update antd to version 3.11.2

src/Button/DigitizeButton/DigitizeButton.jsx
=> Allow style functions as draw style

src/Button/DigitizeButton/DigitizeButton.jsx
Title says it all. See also https://github.com/terrestris/react-geo/pull/959
=> DigitizeButton - Allow style functions as draw style - OL5

src/Grid/FeatureGrid/FeatureGrid.example.md
This fixes the example of the `FeatureGrid` component with a remote source.
=> Fix FeatureGrid (remote source) example

src/HigherOrderComponent/VisibleComponent/VisibleComponent.example.md
This fixes the example of the `VisibleComponent` HOC.
=> Fix VisibleComponent example

package.json
=> fix(package): update react-rnd to version 9.1.1

package.json
=> chore(package): update eslint-plugin-html to version 5.0.3

package.json
=> fix(package): update @terrestris/ol-util to version 2.0.1

package.json
=> Update react to the latest version

src/Panel/Panel/Panel.spec.jsx
Follow up of #1043, fixes test which was ok for travis but fails locally.
Please kindly review @weskamm
=> fix test for onKeyDown method

package.json
=> chore(package): update enzyme-adapter-react-16 to version 1.10.0

package.json
=> chore(package): update antd to version 3.14.1

.travis.yml
The styleguide generated on travis is currently broken, this disables the auto-update (for now).
=> Disable update of gh-pages branch

package.json
=> chore(package): update enzyme-adapter-react-16 to version 1.11.2

.vscode/settings.json
This adds a `settings.json` for VS Code. Currently it's only used to determine and read out our custom-named eslint config file.
=> Add settings.json for VS Code

package.json
=> chore(package): update enzyme-adapter-react-16 to version 1.12.1

src/Button/MeasureButton/MeasureButton.jsx, src/Button/MeasureButton/MeasureButton.spec.jsx
This fixes some minor issues in the `MeasureButton`:
* Remove unneeded state for slightly better performance.
* Remove usage of arrow functions in class methods.
* Rename some listener functions.
* Refactor / split some methods.
* Enhance mobile usability (tooltips with measure results weren't shown).
* Fix #266 (multipleDrawing).
=> Several fixes to the MeasureButton

package.json
This adds the minimal required versions of node and npm to the engines section of the README, see #1120 as well.
Please review @marcjansen.
=> Add engines section, see #1120 as well

package.json
=> chore(package): update antd to version 3.18.1

package.json
=> chore(package): update react-styleguidist to version 9.1.2

package.json, webpack.common.config.js
Fixes configuration for `url-loader` after major release [v2.0.0](https://github.com/webpack-contrib/url-loader/releases/tag/v2.0.0) (details also in https://github.com/webpack-contrib/url-loader/pull/180)
Covers #1163.
=> Fix url-loader config

package.json
=> chore(package): update react-styleguidist to version 9.1.7

package.json
=> chore(package): update react-styleguidist to version 9.1.9

README.md
=> Add note about react-geo-baseclient to README

.ci/run-coveralls.sh, .ci/update-gh-pages.sh, .travis.yml
This (hopefully) reactivates the auto update of the `gh-pages` branch by updating the branch only once (for node v12).
See #1119.
=> Reactivate auto update of gh-pages branch

package.json
=> chore(package): update antd to version 3.19.8

src/Field/ScaleCombo/ScaleCombo.jsx, src/Field/ScaleCombo/ScaleCombo.spec.jsx
=> Fix missing value in scale combo

package-lock.json, package.json
=> Greenkeeper/webpack 4.38.0

package-lock.json, package.json
This updates `react-rnd` to the newest version (10.0.0).
Closes #1207.
=> Update react-rnd to v10.0.0

src/HigherOrderComponent/LoadifiedComponent/LoadifiedComponent.example.md, src/LayerTree/LayerTree.example.md, src/Legend/Legend.spec.jsx, src/Panel/Panel/Panel.jsx
* Filters the prop `collapsed` before passing to child components in `Panel`
* Replaces invalide usage of mapbox TileJSON layers in examples (and tests)
=> Minor fixes

package-lock.json, package.json
=> Greenkeeper/react styleguidist 10.2.0

package.json
This fixes the copying of `*.less` files to the dist folder.
=> Fixes copying of less files to dist

.vscode/launch.json, src/UserChip/UserChip.spec.tsx, src/UserChip/UserChip.tsx
This adds some enhancements to the UserChip class.
- `UserChipProps` extend `AvatarProps`
- props will be passed through to the antd `Avatar`
- `userName` can be a `ReactNode`
=> Enhancements to the UserChip

src/HigherOrderComponent/DropTargetMap/DropTargetMap.tsx, src/HigherOrderComponent/LoadifiedComponent/LoadifiedComponent.tsx, src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.tsx, src/HigherOrderComponent/TimeLayerAware/TimeLayerAware.tsx
This fixes the typings for the higher order components.
Properties of the wrapped components have been invalid before.
=> Fixes typings for higher order components

package-lock.json, package.json
=> Greenkeeper/file loader 5.0.2

package-lock.json, package.json
=> Greenkeeper/xmldom 0.2.1

README.md, package.json
Required due to update to file-loader [v5](https://github.com/webpack-contrib/file-loader/releases/tag/v5.0.0) and url-loader [v3](https://github.com/webpack-contrib/url-loader/releases/tag/v3.0.0).
=> Set minimum required node version to 10.13.0

package-lock.json, package.json
=> Greenkeeper/react styleguidist 10.3.2

package-lock.json, package.json
=> Greenkeeper/coveralls 3.0.9

package-lock.json, package.json
Follow up of https://github.com/terrestris/react-geo/pull/1275
=> Greenkeeper/@types/node 13.1.1

package-lock.json, package.json
=> Greenkeeper/fork ts checker webpack plugin 4.0.2

src/index.ts
Adds missing import and export statements for `TimeLayerSliderComponent`. 
Fixes #1288.
=> Add missing export for TimeLayerSliderPanel component

package-lock.json, package.json, src/CoordinateInfo/CoordinateInfo.tsx
This changes the `INFO_FORMAT` in the `CoordinateInfo` component to `GML2` for broader support of WMS servers.
=> Switch to GML2

package-lock.json, package.json
=> Greenkeeper/np 6.1.0

package-lock.json, package.json
=> Greenkeeper/@types/jest 25.1.2

README.md
This removes the greenkeeper status badge from the README.
=> Remove the greenkeeper status badge

.dependabot/config.yml
Initializes the project specific configuration for `dependabot`. In particular auto merging of PRs is being allowed.
=> Init dependabot configuration

.travis.yml
=> Run travis for node version 14 as well

.github/workflows/on-push-master.yml
See in title. Follow up of #1855.
=> Generate coverage before running coveralls

.github/workflows/on-push-master.yml
Ensures the GITHUB_TOKEN is being used to authenticate against coveralls.
=> Make use of a coveralls action

src/LayerTree/LayerTreeNode/LayerTreeNode.less
=> Make sure tree icons are aligned to the right

src/Legend/Legend.tsx
This adds the option to specify a custom error handler function, when the loading of the legend image failed.
Besides, an error message can be given that will be displayed in case of an load error. 
This will effectively remove the default broken image of the browser.
=> Add error message and custom handler for broken legends

src/Button/DigitizeButton/DigitizeButton.tsx
check if interaction exists before calling setActive
=> check if interaction exists in onToggle

src/Field/NominatimSearch/NominatimSearch.tsx, src/Field/WfsSearchInput/WfsSearchInput.tsx
This allows one to use the Nominatim and WFS search in a headless way, so that no rendering of input fields or results happen.
This becomes useful when implementing your own UI or when combining multiple searches.
=> Allow headless usage of nominatim and wfs search

src/LayerTree/LayerTree.spec.tsx, src/LayerTree/LayerTree.tsx
This fixes some issues with layergroup visibility:
* Before this change, one could not create a tree with an invisible layergroup in it, as the visibility handling for the containing layers was broken (could not be changed)
* When a child layer changed its visibility, the parenting folder was not correctly made visible and in turn, the layer did not become visible. This has changed now. Setting a layer visible will turn on its parenting layer groups in order to really "see" the layer in the map as visible
=> Fix handling visibility of layer groups in tree

package-lock.json, package.json
=> 15.0.0-beta.0

src/UserChip/UserChip.spec.tsx
=> Migrate userChip tests to react-testing-library

src/Button/DigitizeButton/DigitizeButton.tsx
With this PR the invocation of `drawInteractions` for `DigitizeButtons` is improved.
=> Improves invoking the draw interactions

src/CoordinateInfo/CoordinateInfo.spec.tsx, src/Toolbar/Toolbar.spec.tsx, src/Toolbar/Toolbar.tsx
Migrates toolbar and CoordinateInfo tests.
=> Migrate toolbar tests

src/LayerSwitcher/LayerSwitcher.spec.tsx, src/LayerSwitcher/LayerSwitcher.tsx, src/Map/MapComponent/MapComponent.tsx
Adds rtl test for layerswitcher. Adds role `application` to the map component.
=> rewrite test for layer switcher

src/Grid/FeatureGrid/FeatureGrid.example.md
Updates URL and extent of busstops WFS in FeatureGrid demo.
=> repair FeatureGrid demo

jest.config.js, package-lock.json, package.json, src/LayerTree/LayerTree.spec.tsx
This updates antd to it's latest version.
=> Update antd to 4.15.1

src/Button/DigitizeButton/DigitizeButton.jsx
Backport of https://github.com/terrestris/react-geo/pull/2262
=> fix: evaluate style function inside of style function

.releaserc, package.json
Extract npx release config to `.releaserc` file.
@terrestris/devs
=> Introduce .releaserc file 

.releaserc, package.json
=> Fix typo in .releaserc

src/Button/DrawButton/DrawButton.spec.tsx, src/Button/SelectFeaturesButton/SelectFeaturesButton.example.md, src/Button/SelectFeaturesButton/SelectFeaturesButton.spec.tsx, src/Button/SelectFeaturesButton/SelectFeaturesButton.tsx, src/Util/DigitizeUtil.ts, src/Util/rtlTestUtils.tsx
This adds a button that gets passed an array of layers from which to select vector features from. This is a building block for the upcoming CopyButton, DeleteButton and ModifyButton.
It renames the `renderInContext` method to `renderInMapContext` to make it a little clearer.
=> Add SelectFeaturesButton

src/Button/ZoomButton/ZoomButton.spec.tsx, src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.spec.tsx, src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.tsx
Migrates ZoomButton and AddWmsLayerEntry tests to work with testing-library.
=> Migrate ZoomButton and AddWmsLayerEntry tests

README.md
This PR suggests to remove several broken badges from the `README.md`-file:
State before:
State after:
=> chore: Remove broken badges from README.md

.github/workflows/release.yaml
This tries to fix #2313 by providing a custom personal access token for creation of the release (as suggested [here](https://github.com/semantic-release/github#github-authentication)).
Please note @terrestris/devs.
#2313.
=> Trigger release events by providing custom PAT

src/Button/DeleteButton/DeleteButton.tsx, src/Button/ModifyButton/ModifyButton.tsx, src/FeatureLabelModal/FeatureLabelModal.tsx, src/HigherOrderComponent/LoadifiedComponent/LoadifiedComponent.tsx, src/HigherOrderComponent/MappifiedComponent/MappifiedComponent.tsx, src/HigherOrderComponent/VisibleComponent/VisibleComponent.tsx, src/Hook/useMap.ts, src/index.ts, styleguide.config.js
This adds some missing default exports and adds all components to the global export object.
--
=> Missing global exports

src/Button/DrawButton/DrawButton.tsx, src/Button/GeoLocationButton/GeoLocationButton.tsx, src/Button/MeasureButton/MeasureButton.tsx, src/Button/ModifyButton/ModifyButton.tsx, src/Button/SelectFeaturesButton/SelectFeaturesButton.tsx, src/Button/ToggleButton/ToggleButton.tsx
In particular, this PR includes:
* mark props of `ToggleButton` as `Partial` in all draw buttons
* De-structure `geodesic` prop in `MeasureButton`
* Listen to correct interaction event on translate end in `ModifyButton`
=> Measurement button fixes

.github/workflows/release.yaml, .releaserc, src/Button/DigitizeButton/DigitizeButton.tsx
Configured a `15.x.x` maintenance branch with a small `DigitizeButton` fix. The version `15.4.1` already did get released.
=> Digitize button fix

src/Field/NominatimSearch/NominatimSearch.tsx
This adds support for [localized nominatim responses](https://nominatim.org/release-docs/develop/api/Search/#language-of-results) via the `searchResultLanguage` prop.
--
=> Add support for localized nominatim responses

src/Button/ZoomButton/ZoomButton.tsx
This adds a better check for the current zoom to the ZoomButton.
=> Fixes ZoomButton

package-lock.json, package.json, src/Button/PrintButton/PrintButton.tsx, webpack.common.config.js
Allows to set inkmap settings via PrintButton props. Also fixes typing issues.
=> fix: make print settings configurable

src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
This refactors `<SearchResultsPanel>` to allow specifying the order of the result categories. At the same time, the property `features` was renamed to `searchResults` for better readability.
BREAKING CHANGE: The property `features` was replaced with
`searchResults` and its type was changed to `Category[]`.
=> feat: allow ordering searchResult categories

src/Panel/SearchResultsPanel/SearchResultsPanel.spec.tsx, src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
`actionsCreator` allows for adding arbitrary actions (e.g. buttons) to each search result item.
=> feat: add new property actionsCreator to SearchResultsPanel

package-lock.json, package.json
Please note @terrestris/devs.
Updates ol-util to 7.3.0. I tagged the commit as a fix because I need a new release. 
- [] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally).
=> fix: update ol-util to 7.3.0

src/Panel/SearchResultsPanel/SearchResultsPanel.tsx
Take map size into account while fitting to geometry extent.
=> Better fit to geometry extent on search result click

src/CoordinateInfo/CoordinateInfo.tsx
This updates the `CoordinateInfo` component to accept the optional props/callback functions `onSuccess` (called if all features are fetched successfully via `GetFeatureInfo`) and `onError` (called if an error occured while fetching the features).
--
=> Add props onSuccess and onError in `CoordinateInfo`

.gitignore, package-lock.json, package.json, src/Grid/AgFeatureGrid/AgFeatureGrid.tsx
This PR updates `aggrid` (fixes broken PR https://github.com/terrestris/react-geo/pull/2872) and  `inkmap` dependency. In addition, IntelliJ's `iml` files are added to ignored ones.
=> Dependency updates for aggrid and inkmap

src/Grid/AgFeatureGrid/AgFeatureGrid.tsx
=> Catch some potential NP on feature grid

src/CoordinateInfo/CoordinateInfo.tsx
In cases with multiple unknown layer names (which may occur on `GetFeatureInfo` requests on raster-based layers), the former implementation merged all features in a single object entry making it impossible to distinguish the source.
--
=> CoordinateInfo: Mark FeatureCollection from unknown layers with non-empty identifier

README.md
=> chore: update link to ant design docs

package-lock.json, package.json
Update to latest ol-util version. 
=> chore: bump ol-util to 10.2.0

README.md
Fixes the badge (see [here](https://github.com/badges/shields/issues/8671) for details).
--
=> Fix the GitHub action badge

src/Panel/SearchResultsPanel/SearchResultsPanel.spec.tsx
=> Minor lint fixes

src/Legend/Legend.tsx
Refactor the legend component as FC.
- [ x I have followed the [guidelines for contributing](https://github.com/terrestris/react-geo/blob/main/CONTRIBUTING.md).
=> chore: refactor legend as FC

src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.tsx, src/Container/AddWmsPanel/AddWmsPanel.example.md, src/Container/AddWmsPanel/AddWmsPanel.less, src/Container/AddWmsPanel/AddWmsPanel.spec.tsx, src/Container/AddWmsPanel/AddWmsPanel.tsx
Transforms `AddWmsPanel` with its child component `AddWmsEntry` to functional component.
=> Refactor AddWmsPanel component

.github/workflows/release.yaml
See title.
Plz review @terrestris/devs 
=> fix: set correct node version for release pipeline as well

src/BackgroundLayerChooser/BackgroundLayerChooser.tsx
Uses Property correctly if set.
=> fix: makes initalSelectedLayer work

src/Field/NominatimSearch/NominatimSearch.tsx
This PR allows to pass custom `onChange` functions to `NominatimSearch`. This is especially useful when it's used in a `Form`, e.g.
```
<Form
onValuesChange={(_, values) => {
console.log('All values', values);
}}
>
<Form.Item
name="location"
>
<NominatimSearch map={map} />
</Form.Item>
</Form>
```
=> NominatimSearch: allow custom onChange implementations

src/Button/ZoomButton/ZoomButton.example.md, src/Button/ZoomButton/ZoomButton.spec.tsx, src/Button/ZoomButton/ZoomButton.tsx, src/Button/ZoomToExtentButton/ZoomToExtentButton.example.md, src/Button/ZoomToExtentButton/ZoomToExtentButton.spec.tsx, src/Button/ZoomToExtentButton/ZoomToExtentButton.tsx
=> Refactor `ZoomButton` and `ZoomToExtentButtons` to function components

src/CircleMenu/CircleMenu.example.md, src/CircleMenu/CircleMenu.less, src/CircleMenu/CircleMenu.spec.tsx, src/CircleMenu/CircleMenu.tsx, src/CircleMenu/CircleMenuItem/CircleMenuItem.less, src/CircleMenu/CircleMenuItem/CircleMenuItem.spec.tsx, src/CircleMenu/CircleMenuItem/CircleMenuItem.tsx
This refactors the `CircleMenu`  to a function component.
=> Refactor `CircleMenu` to function component

src/Slider/LayerTransparencySlider/LayerTransparencySlider.example.md, src/Slider/LayerTransparencySlider/LayerTransparencySlider.spec.tsx, src/Slider/LayerTransparencySlider/LayerTransparencySlider.tsx
This refactors the `LayerTransparencySlider` to a function component.
=> Refactor `LayerTransparencySlider` to function component

src/Grid/PropertyGrid/PropertyGrid.example.md, src/Grid/PropertyGrid/PropertyGrid.spec.tsx, src/Grid/PropertyGrid/PropertyGrid.tsx
This refactors the `PropertyGrid` to a function component.
=> Refactor `PropertyGrid` to function component 

package-lock.json, package.json
Reverts terrestris/react-geo#3764
=> Revert "build(deps-dev): bump @commitlint/cli from 18.4.3 to 19.0.1"

src/Button/CopyButton/CopyButton.tsx, src/Button/DeleteButton/DeleteButton.tsx, src/Button/DrawButton/DrawButton.tsx, src/Button/ModifyButton/ModifyButton.tsx, src/Button/SelectFeaturesButton/SelectFeaturesButton.tsx
=> Use digitize related hooks from react-util

src/CoordinateInfo/CoordinateInfo.example.md, src/CoordinateInfo/CoordinateInfo.spec.tsx, src/CoordinateInfo/CoordinateInfo.tsx
See title.
In addition, the `CoordinateInfo` component is migrated to a function component.
Depends on https://github.com/terrestris/react-util/pull/592
- [] Refactoring (no functional changes, no api changes)
=> Feature: use coordinateInfo hook

src/Button/RotationButton/RotationButton.example.md, src/Button/RotationButton/RotationButton.spec.tsx, src/Button/RotationButton/RotationButton.tsx
Added a RotationButton for rotating the map with shift and drag.
=> feat: add RotationButton

src/Button/RotationButton/RotationButton.example.md, src/Button/RotationButton/RotationButton.spec.tsx, src/Button/RotationButton/RotationButton.tsx
newest update from main branch added
=> Rg future update

src/Button/RotationButton/RotationButton.tsx
fixed the tooltip property of the rotation button
https://github.com/terrestris/react-geo/pull/3782
=> fix: tooltip for RotationButton

styleguide.config.js
This includes the [`reset.css`](https://ant.design/docs/react/migration-v5#technology-adjustment) of antd in the styleguide to harmonize styles between components and example markup.
--
=> build: include antd css reset

src/Map/FloatingMapLogo/FloatingMapLogo.example.md, src/Map/FloatingMapLogo/FloatingMapLogo.less
Refactors the `FloatingMapLogo` example to a function component.
Requires [#681](https://github.com/terrestris/react-util/pull/681).
=> Refactor `FloatingMapLogo` example

package.json, src/Button/CopyButton/CopyButton.tsx, src/Button/DeleteButton/DeleteButton.tsx, src/CircleMenu/CircleMenu.spec.tsx, src/CoordinateInfo/CoordinateInfo.spec.tsx, src/Field/CoordinateReferenceSystemCombo/CoordinateReferenceSystemCombo.spec.tsx, src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.spec.tsx, src/Slider/LayerTransparencySlider/LayerTransparencySlider.spec.tsx, tsconfig.json
This includes the `*.spec` files in `tsc` to enable type checking during development. To emit the files in the `dist` directory they will be filtered out in the `build:declaration` script.
--
=> Enable type checking for spec files as well

package-lock.json, package.json, src/CoordinateInfo/CoordinateInfo.example.md
A new wfs layer and feature-info query is introduced into the example.
the following MR needs to be considered:
https://github.com/terrestris/react-util/pull/692
=> feat: adds a wfs layer and feature-info

src/Context/MapContext/MapContext.tsx, src/Hook/useMap.ts
=> docs: explain why useMap.ts and MapContext.tsx are empty

package-lock.json, package.json, src/Container/AddWmsPanel/AddWmsLayerEntry/AddWmsLayerEntry.tsx, src/Container/AddWmsPanel/AddWmsPanel.example.md, src/Container/AddWmsPanel/AddWmsPanel.tsx, src/Legend/Legend.tsx, src/Panel/TimeLayerSliderPanel/TimeLayerSliderPanel.tsx
=> feat: use `WmsLayer` from `ol-util` instead of `react-util`

src/Grid/PropertyGrid/PropertyGrid.example.md, src/Grid/PropertyGrid/PropertyGrid.spec.tsx, src/Grid/PropertyGrid/PropertyGrid.tsx
This ports #3849 to the next branch.
=> Render urls as anchor element

README.md
=> fix: add build info to readme

src/Grid/FeatureGrid/FeatureGrid.tsx, src/LayerTree/LayerTree.less, src/LayerTree/LayerTree.spec.tsx, src/LayerTree/LayerTree.tsx
makes the content of the tree node clickable
=> fix(LayerTree): make contents of title clickable

src/Grid/PropertyGrid/PropertyGrid.less
=> fix: make property grid tighter

.releaserc
This (re-)enables major releases on the main branch
=> ci: enable major release

package-lock.json, package.json
=> fix: update react-util

package-lock.json, package.json, src/CoordinateInfo/CoordinateInfo.example.md
Suggest to use `useCoordinateInfo` directly and show example.
Upgrade Notes were also updated: https://github.com/terrestris/react-geo/wiki/Version-24.0.0-Upgrade-Notes
=> fix(CoordinateInfo): update docs and react-util

src/Grid/FeatureGrid/FeatureGrid.example.md
This MR fixes a typo and is used for a new release since the related requests did not trigger the semantic release. 
https://github.com/terrestris/react-geo/pull/3896
=> feat: fixing typo

.npmrc
In this PR the `engine-strict` config is removed. Herewith, the dependabot dependency updates should work again.
=> chore: remove engine-strict config

.husky/commit-msg
=> fix: husky deprecated call

src/Grid/FeatureGrid/FeatureGrid.tsx
This MR adds a column filter that can also be used to define the column order. If the attribute is set, all columns defined in the array will be displayed. If the attribute is not set, all columns will be shown.
Attributes defined in the blacklist will be ignored from the list anyways.
Dragging a column works as expected.
=> feat: adds a column filter

package-lock.json, package.json, src/Grid/AgFeatureGrid/AgFeatureGrid.tsx
Uses modules instead of packages. See https://www.ag-grid.com/react-data-grid/modules/
Breaking change:
- the modules used now have to be registered. Only relevant if you are using CSV export or Infinite Row Model. See https://www.ag-grid.com/react-data-grid/modules/#registering-ag-grid-modules
- Imports of AG Grid might have to be adjusted. Otherwise ag-grid will be included twice in your bundle. See https://www.ag-grid.com/react-data-grid/modules/#mixing-packages-and-modules
=> Use ag-grid modules

package-lock.json, package.json
Please note @terrestris/devs .
=> chore: update ag-grid to 32.3.2

src/BackgroundLayerPreview/BackgroundLayerPreview.tsx
This PR introduces support for nested LayerGroups in the background layer management for the component `BackgroundLayerPreview`.
=> Support nested LayerGroups for background layer management

src/LayerSwitcher/LayerSwitcher.tsx
This PR fixes a bug in the zoom behavior of the main map (as done for v24 in https://github.com/terrestris/react-geo/pull/4202) when the LayerSwitcher is included. Previously a too small scale was reached when zooming in. The user expected to zoom closer to the selected area by dragging a box.
This is achieved by synchronizing the view between the main map and the preview map, instead of using the same view:
Old behavior:  
New behavior:  
This PR will release a fix for the current version of react-geo.
- #4202 
=> Fixes a zoom error in LayerSwitcher (current verison)

package-lock.json, package.json, src/Button/DrawCutButton/DrawCutButton.tsx
=> fix(deps): update react-util
